// Each book has:
//   t: title, a: author, g: genre, d: description
//   c: prose complexity (1-5)
//   p: genre depth (1-5)
//   s: { name: "series name", n: position_in_series, total: total_books } [optional]
// 1 = approachable, 5 = challenging
export const BOOKS_DATA = [
  // FOLK HORROR
  { t: "The Ritual", a: "Adam Nevill", g: "Folk Horror", c: 3, p: 4, d: "Four friends on a Scandinavian hiking trip take a shortcut through ancient woods that conceal something pagan and patient." },
  { t: "Starve Acre", a: "Andrew Michael Hurley", g: "Folk Horror", c: 4, p: 4, d: "After their son's death, a couple unearths something terrible from the soil of their Yorkshire farm." },
  { t: "The Reddening", a: "Adam Nevill", g: "Folk Horror", c: 3, p: 4, d: "A coastal English town hides a prehistoric cult and a hunger that has never stopped." },
  { t: "Monumental", a: "Adam Nevill", g: "Folk Horror", c: 3, p: 4, d: "Pagan terror among standing stones from the author of The Ritual." },
  { t: "Withered Hill", a: "David Barnett", g: "Folk Horror", c: 3, p: 3, d: "A woman wakes in a remote English village where everyone seems to know her, and the rituals have already begun." },
  { t: "The Fisherman", a: "John Langan", g: "Folk Horror", c: 4, p: 5, d: "Two widowers find a fishing spot upstate with a dark history that bleeds into the present." },
  { t: "Harvest Home", a: "Thomas Tryon", g: "Folk Horror", c: 3, p: 3, d: "A family moves to a picturesque New England village whose harvest traditions hide horror." },
  { t: "The Year of the Witching", a: "Alexis Henderson", g: "Folk Horror", c: 2, p: 3, d: "In a puritanical settlement, a young woman is called by the witches of the surrounding dark wood." },
  { t: "Mere", a: "Danielle Giles", g: "Folk Horror", c: 4, p: 4, d: "Forbidden love and ancient secrets in a medieval English convent on the edge of the fens." },
  { t: "Grey Dog", a: "Elliott Gish", g: "Folk Horror", c: 4, p: 4, d: "A schoolteacher in a remote 1901 settlement begins to sense something old and watching in the woods." },
  { t: "Gather the Daughters", a: "Jennie Melamed", g: "Folk Horror", c: 3, p: 4, d: "On an isolated island, girls are raised under strict rules — until one summer breaks them open." },
  { t: "The Hollow Kind", a: "Andy Davidson", g: "Folk Horror", c: 4, p: 4, d: "Southern Gothic folk horror about a turpentine plantation, ancestral debt, and what lives in the pines." },
  { t: "Foxash", a: "Kate Worsley", g: "Folk Horror", c: 4, p: 4, d: "Wonderfully atmospheric and deeply unsettling — Sarah Waters." },
  { t: "Damnable Tales", a: "Richard Wells (ed.)", g: "Folk Horror", c: 3, p: 4, d: "A folk horror anthology gathering classic and contemporary tales of the haunted land." },
  { t: "Lost in the Garden", a: "Adam S. Leslie", g: "Folk Horror", c: 4, p: 5, d: "Three women drift through a strange unchanging English summer toward a village that may not exist." },
  { t: "The Bog Wife", a: "Kay Chronister", g: "Folk Horror", c: 4, p: 4, d: "Five siblings tied by a centuries-old pact to the cranberry bog that sustains them." },
  { t: "Something in the Walls", a: "Daisy Pearce", g: "Folk Horror", c: 2, p: 3, d: "A child psychologist is called to a Cornish village where a girl claims a witch lives behind her walls." },
  { t: "Small Angels", a: "Lauren Owen", g: "Folk Horror", c: 4, p: 4, d: "A wedding returns an estranged sister to the haunted woods of her childhood." },
  { t: "The Only Good Indians", a: "Stephen Graham Jones", g: "Folk Horror", c: 4, p: 4, d: "Four Blackfeet men are stalked by an entity born from a hunt they should never have taken." },
  { t: "The Buffalo Hunter Hunter", a: "Stephen Graham Jones", g: "Folk Horror", c: 4, p: 4, d: "A vampire's confession across the American West, soaked in vengeance and memory." },
  { t: "Slewfoot", a: "Brom", g: "Folk Horror", c: 3, p: 4, d: "A young widow and a horned forest god in 1666 New England." },

  // GOTHIC & HAUNTED HOUSES
  { t: "The House on Abigail Lane", a: "Kealan Patrick Burke", g: "Gothic & Haunted Houses", c: 2, p: 3, d: "Every family who lives in this house leaves changed — or doesn't leave at all." },
  { t: "Man, F*ck This House", a: "Brian Asman", g: "Gothic & Haunted Houses", c: 2, p: 2, d: "A suburban family's new home is, increasingly, not okay." },
  { t: "How to Sell a Haunted House", a: "Grady Hendrix", g: "Gothic & Haunted Houses", c: 2, p: 2, d: "Estranged siblings must clear out their dead parents' home — and the puppet collection inside it." },
  { t: "Within These Walls", a: "Ania Ahlborn", g: "Gothic & Haunted Houses", c: 2, p: 3, d: "A struggling writer moves into the house of a dead cult leader to write his story." },
  { t: "Ghost Mother", a: "Kelly Dwyer", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A grieving woman moves into a Victorian house with a previous occupant who refuses to leave." },
  { t: "House of Beth", a: "Kerry Cullen", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A queer woman returns to her hometown, into a marriage and a house that won't stay still." },
  { t: "A Good House for Children", a: "Kate Collins", g: "Gothic & Haunted Houses", c: 4, p: 4, d: "Motherhood and madness in a haunted coastal English mansion." },
  { t: "The Grip of It", a: "Jac Jemc", g: "Gothic & Haunted Houses", c: 4, p: 4, d: "A young couple's new house has stains that move and walls that breathe." },
  { t: "We Live Here Now", a: "Sarah Pinborough", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A couple recovering from tragedy buys a Dartmoor house with a presence that refuses to share." },
  { t: "The Remaking", a: "Clay Chapman", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "The story of a murdered witch and her daughter, retold across centuries until it bites back." },
  { t: "How to Fake a Haunting", a: "Christa Carmen", g: "Gothic & Haunted Houses", c: 2, p: 3, d: "A reality show fakes a haunting in a house that doesn't appreciate being mocked." },
  { t: "In the House in the Dark of the Woods", a: "Laird Hunt", g: "Gothic & Haunted Houses", c: 4, p: 4, d: "A Puritan woman wanders into a fairy tale she cannot wake from." },
  { t: "Hemlock & Silver", a: "T. Kingfisher", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A poison expert is summoned to investigate a queen's slow death, and a story you may recognize unfolds." },
  { t: "The Sundial", a: "Shirley Jackson", g: "Gothic & Haunted Houses", c: 4, p: 4, d: "A wealthy family is told the world will end — and barricades inside the family estate to wait." },
  { t: "Diavola", a: "Jennifer Thorne", g: "Gothic & Haunted Houses", c: 2, p: 3, d: "A dysfunctional family's Tuscan villa vacation goes very wrong, very fast." },
  { t: "The Caretaker", a: "Marcus Kliewer", g: "Gothic & Haunted Houses", c: 2, p: 3, d: "A live-in caregiver discovers her elderly employer's mansion is hiding far worse than dementia." },
  { t: "Incidents Around the House", a: "Josh Malerman", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "An eight-year-old's account of the Other Mommy living in her closet." },
  { t: "The Twisted Ones", a: "T. Kingfisher", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "Cleaning out grandmother's hoarder house in the Carolina mountains turns up something that shouldn't exist." },
  { t: "We Came to Welcome You", a: "Vincent Tirado", g: "Gothic & Haunted Houses", c: 2, p: 3, d: "A Black queer couple moves into a gated community that very much wants them to assimilate." },
  { t: "The Hacienda", a: "Isabel Cañas", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A Mexican mansion after independence, a new bride, and a priest who knows exorcism." },
  { t: "The House of Gardenias", a: "Isabel Cañas", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "Gothic mystery in 1920s Mexico from the author of The Hacienda." },
  { t: "The Haunting of Alejandra", a: "V. Castro", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A Mexican-American mother fights La Llorona — and the lineage of women she has consumed." },
  { t: "Bochica", a: "Carolina Flórez-Cerchiaro", g: "Gothic & Haunted Houses", c: 3, p: 3, d: "A Colombian hotel haunting bound up with colonial history and indigenous myth." },
  { t: "The House at the End of Needless Street", a: "Catriona Ward", g: "Gothic & Haunted Houses", c: 4, p: 4, d: "A man, his daughter, and a cat — all of whom may be lying about everything." },

  // SAPPHIC & FEMINIST GOTHIC
  { t: "Hungerstone", a: "Kat Dunn", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A fierce sapphic reimagining of Carmilla, soaked in iron and hunger." },
  { t: "Linghun", a: "Ai Jiang", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "Families compete for haunted houses in a town that runs on grief." },
  { t: "Model Home", a: "Rivers Solomon", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "A Black queer family confronts the haunted McMansion that shaped them." },
  { t: "Our Wives Under the Sea", a: "Julia Armfield", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "A submarine mission goes wrong, and the wife who returns is no longer entirely a wife." },
  { t: "White is for Witching", a: "Helen Oyeyemi", g: "Sapphic & Feminist Gothic", c: 5, p: 5, d: "A Dover bed-and-breakfast that consumes the women of one family." },
  { t: "My Darling Dreadful Thing", a: "Johanna van Veen", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A spiritualist's daughter, a baroness, and the spirit bound between them." },
  { t: "Blood on Her Tongue", a: "Johanna van Veen", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "Twin sisters, a Dutch bog body, and a possession that may be love." },
  { t: "Feast While You Can", a: "Mikaella Clements & Onjuli Datta", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "Brilliantly visceral queer horror set in an Italian mountain town with an old hunger." },
  { t: "Mrs S", a: "K Patrick", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "A summer of obsession between a new matron and the headmaster's wife at a girls' boarding school." },
  { t: "Lady Macbeth", a: "Ava Reid", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A reclaiming of Shakespeare's witch-queen, written in blood." },
  { t: "Weyward", a: "Emilia Hart", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "Three women across centuries, bound by a witchy bloodline." },
  { t: "The Manningtree Witches", a: "A. K. Blakemore", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "The English witch trials of 1645, told by the women on the gallows side of them." },
  { t: "The Lamb", a: "Lucy Rose", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A mother and daughter living in the woods welcome strangers — and eat them." },
  { t: "Saint Catherine", a: "Anna Meyer", g: "Sapphic & Feminist Gothic", c: 3, p: 4, d: "Medieval mystic agony and queer desire in a convent." },
  { t: "This Is My Body", a: "Lindsay King-Miller", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "Catholic horror about queer girls, transubstantiation, and what we feed each other." },
  { t: "Mister Magic", a: "Kiersten White", g: "Sapphic & Feminist Gothic", c: 2, p: 3, d: "Survivors of a cult children's show reunite to face the thing they helped trap." },
  { t: "Where I End", a: "Sophie White", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "An Irish island, a bedridden mother, and a daughter who has never been allowed to leave." },
  { t: "Helpmeet", a: "Naben Ruthnum", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A wife caring for her dying husband finds his decay becoming something else." },
  { t: "The Bewitching", a: "Silvia Moreno-Garcia", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A graduate student researching a forgotten horror writer uncovers a witch's century-long pursuit." },
  { t: "Nightbitch", a: "Rachel Yoder", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A new mother becomes increasingly certain she is turning into a dog." },
  { t: "And Then She Fell", a: "Alicia Elliott", g: "Sapphic & Feminist Gothic", c: 4, p: 4, d: "A Mohawk new mother on the edge of postpartum psychosis, or revelation." },
  { t: "Old Soul", a: "Susan Barker", g: "Sapphic & Feminist Gothic", c: 3, p: 3, d: "A woman across continents who never seems to age, and the ones she leaves behind." },

  // VAMPIRES
  { t: "Sueño del Fevre", a: "George R. R. Martin", g: "Vampires", c: 3, p: 3, d: "A Mississippi riverboat in 1857, its captain, and the elegant vampire who books passage." },
  { t: "The Southern Book Club's Guide to Slaying Vampires", a: "Grady Hendrix", g: "Vampires", c: 2, p: 2, d: "A 90s Charleston book club realizes their charming new neighbor is feeding on local children." },
  { t: "Ciertas cosas oscuras", a: "Silvia Moreno-Garcia", g: "Vampires", c: 3, p: 3, d: "1990s Mexico City: a journalist, a runaway, and a vampire descended from Aztec bloodlines." },
  { t: "The Vampire of Ropraz", a: "Jacques Chessex", g: "Vampires", c: 4, p: 4, d: "A short, brutal novella of grave-robbing in 1903 Switzerland." },
  { t: "Malasangre", a: "Michelle Roche Rodríguez", g: "Vampires", c: 4, p: 4, d: "A young woman in 1920s Caracas discovers her vampiric inheritance during the oil boom." },
  { t: "Fledgling", a: "Octavia E. Butler", g: "Vampires", c: 3, p: 4, d: "A genetically engineered vampire-child wakes with no memory and the urge to bind humans to her." },
  { t: "The Hunger", a: "Alma Katsu", g: "Vampires", c: 3, p: 3, d: "The Donner Party with something else stalking the snow." },
  { t: "Dire Bound", a: "Sable Sorensen", g: "Vampires", c: 2, p: 2, d: "Enemies-to-lovers wolf fantasy that detonated on TikTok." },
  { t: "Hadriana in All My Dreams", a: "René Depestre", g: "Vampires", c: 4, p: 5, d: "A Haitian bride dies at the altar — or does she? Carnival, zombification, voudou." },
  { t: "Immortal Dark", a: "Tigest Girma", g: "Vampires", c: 2, p: 3, d: "A dark academia vampire romance starring a Black orphan and the immortal who wants her dead." },
  { t: "The Lesser Dead", a: "Christopher Buehlman", g: "Vampires", c: 3, p: 3, d: "1978 NYC underground vampires meet something younger and worse." },
  { t: "Bury Our Bones in the Midnight Soil", a: "V. E. Schwab", g: "Vampires", c: 3, p: 3, d: "Three women across five centuries, bound by hunger and by each other." },
  { t: "A Dowry of Blood", a: "S.T. Gibson", g: "Vampires", c: 3, p: 3, d: "Constanta tells the story of her marriage to Dracula — and to the others he gathered." },
  { t: "Blackwater: The Complete Saga", a: "Michael McDowell", g: "Vampires", c: 3, p: 3, d: "Alabama family saga with a wife who emerged from the river and isn't quite human." },
  { t: "El imperio del vampiro", a: "Jay Kristoff", g: "Vampires", c: 3, p: 3, s: { name: "Empire of the Vampire", n: 1, total: 3 }, d: "Empire of the Vampire — grimdark, brutal, and beautifully bleak." },

  // WITCHES
  { t: "Practical Magic", a: "Alice Hoffman", g: "Witches", c: 3, p: 3, s: { name: "Practical Magic", n: 3, total: 4 }, d: "Two sisters in a Massachusetts town inherit a family curse that forbids love." },
  { t: "Equal Rites", a: "Terry Pratchett", g: "Witches", c: 2, p: 2, s: { name: "Discworld", n: 3, total: 41 }, d: "Granny Weatherwax and the first girl ever born a wizard." },
  { t: "Cackle", a: "Rachel Harrison", g: "Witches", c: 2, p: 2, d: "A woman recovering from a breakup befriends a glamorous witch in a small town." },
  { t: "Witchcraft for Wayward Girls", a: "Grady Hendrix", g: "Witches", c: 2, p: 3, d: "A 1970s home for unwed mothers gets visited by a witch with a tempting book." },
  { t: "Glass Girls", a: "Danie Shokoohi", g: "Witches", c: 3, p: 3, d: "Iranian-American sisters and a grimoire that wants only one of them." },
  { t: "The Last Witch", a: "C. J. Cooke", g: "Witches", c: 3, p: 3, d: "The 17th-century witch trials of the Scottish Highlands, told from the gallows." },
  { t: "Yo, Tituba, la bruja negra de Salem", a: "Maryse Condé", g: "Witches", c: 4, p: 4, d: "The Caribbean enslaved woman written out of Salem, finally given voice." },
  { t: "The Wax Child", a: "Olga Ravn", g: "Witches", c: 4, p: 4, d: "A wax doll given a witch's name narrates 17th-century Danish witch trials." },
  { t: "HEX", a: "Thomas Olde Heuvelt", g: "Witches", c: 2, p: 3, d: "A Hudson Valley town quietly tolerates its centuries-old witch — until the internet finds her." },
  { t: "The Great Witch of Brittany", a: "Louisa Morgan", g: "Witches", c: 3, p: 3, d: "A romani orphan in 18th-century France inherits a witchcraft her family long forgot." },
  { t: "Spear", a: "Nicola Griffith", g: "Witches", c: 4, p: 4, d: "A queer Arthurian retelling rooted in Welsh myth and forest magic." },
  { t: "Greenteeth", a: "Molly O'Neill", g: "Witches", c: 2, p: 3, d: "A bog-witch, a girl, and the village that wants both of them dead." },

  // LATIN AMERICAN HORROR & LITERARY
  { t: "Nuestra parte de noche", a: "Mariana Enriquez", g: "Latin American Horror & Literary", c: 5, p: 5, d: "A father and son flee a Buenos Aires cult that demands the boy's body." },
  { t: "Las cosas que perdimos en el fuego", a: "Mariana Enríquez", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Argentine short fiction of femicide, addiction, and ghosts that taste of the dictatorship." },
  { t: "Los peligros de fumar en la cama", a: "Mariana Enriquez", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Earlier Enríquez stories — feral teenage girls, dead children, decaying neighborhoods." },
  { t: "Temporada de huracanes", a: "Fernanda Melchor", g: "Latin American Horror & Literary", c: 5, p: 5, d: "A witch is murdered in a Veracruz village and the village explains itself in long, breathless paragraphs." },
  { t: "Pedro Páramo", a: "Juan Rulfo", g: "Latin American Horror & Literary", c: 5, p: 5, d: "A son returns to his father's town to find every inhabitant has been dead for years." },
  { t: "El obsceno pájaro de la noche", a: "José Donoso", g: "Latin American Horror & Literary", c: 5, p: 5, d: "Chilean masterpiece of fevered, monstrous, claustrophobic prose." },
  { t: "Cometierra", a: "Dolores Reyes", g: "Latin American Horror & Literary", c: 3, p: 4, d: "An Argentine girl eats earth and sees the dead — including the disappeared." },
  { t: "Carcoma", a: "Layla Martínez", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Two generations of women in a Spanish village house haunted by class rage." },
  { t: "Sacrificios humanos", a: "María Fernanda Ampuero", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Ecuadorian short fiction about migration, domestic violence, and the violence done to bodies." },
  { t: "Nuestra piel muerta", a: "Natalia García Freire", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Ecuadorian gothic about a son returning to a house overrun by his father's followers." },
  { t: "Chamanes eléctricos en la fiesta del sol", a: "Mónica Ojeda", g: "Latin American Horror & Literary", c: 5, p: 5, d: "Andean noise music festival, ayahuasca, and friendship in Mónica Ojeda's lush prose." },
  { t: "Nefando", a: "Mónica Ojeda", g: "Latin American Horror & Literary", c: 5, p: 5, d: "A Barcelona apartment, a video game, and the unspeakable thing five young people share." },
  { t: "Furia", a: "Clyo Mendoza", g: "Latin American Horror & Literary", c: 5, p: 5, d: "Two Mexican deserters wander a desert where bullets travel through time." },
  { t: "Tierra fresca de su tumba", a: "Giovanna Rivero", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Bolivian gothic stories of migration, blood, and the dead who refuse to stay." },
  { t: "El cielo de la selva", a: "Elaine Vilar Madruga", g: "Latin American Horror & Literary", c: 4, p: 4, d: "A Cuban matriarch, the jungle that surrounds her family, and the rot that travels through it." },
  { t: "Aura", a: "Carlos Fuentes", g: "Latin American Horror & Literary", c: 4, p: 5, d: "A young historian is hired by an old widow in Mexico City — and falls for her niece who isn't a niece." },
  { t: "La amortajada", a: "María Luisa Bombal", g: "Latin American Horror & Literary", c: 4, p: 5, d: "A dead woman narrates her own wake, reviewing the lives that touched hers." },
  { t: "Las niñas del naranjel", a: "Gabriela Cabezón Cámara", g: "Latin American Horror & Literary", c: 5, p: 5, d: "A queer Argentine retelling of the Catalina de Erauso legend, lush and lawless." },
  { t: "Los recuerdos del porvenir", a: "Elena Garro", g: "Latin American Horror & Literary", c: 5, p: 5, d: "A Mexican town narrates its own occupation during the Cristero War." },
  { t: "Oficio de tinieblas", a: "Rosario Castellanos", g: "Latin American Horror & Literary", c: 4, p: 5, d: "An indigenous uprising in 1930s Chiapas, told without sentimentality or distance." },
  { t: "Lotería: Stories", a: "Cynthia Pelayo", g: "Latin American Horror & Literary", c: 3, p: 3, d: "Latin American horror stories shuffled like the lottery deck they're named for." },
  { t: "Five Midnights", a: "Ann Dávila Cardinal", g: "Latin American Horror & Literary", c: 2, p: 3, d: "El Cuco hunts five friends in San Juan, Puerto Rico." },
  { t: "Lobizona", a: "Romina Garber", g: "Latin American Horror & Literary", c: 2, p: 2, s: { name: "Wolves of No World", n: 1, total: 2 }, d: "An undocumented Argentine girl in Miami discovers she is a werewolf — and illegal among both worlds." },
  { t: "Goddess of Filth", a: "V. Castro", g: "Latin American Horror & Literary", c: 2, p: 3, d: "Five Latina friends summon something during a séance and one becomes more than she was." },
  { t: "Pinata", a: "Leopoldo Gout", g: "Latin American Horror & Literary", c: 2, p: 3, d: "A Mexican-American mother and daughters disturb something at a restoration site in Tulancingo." },
  { t: "Lapvona", a: "Ottessa Moshfegh", g: "Latin American Horror & Literary", c: 4, p: 4, d: "Famine, faith, and feudal cruelty in a medieval village." },

  // KOREAN, JAPANESE & EAST ASIAN LIT
  { t: "Pachinko", a: "Min Jin Lee", g: "Korean, Japanese & East Asian Lit", c: 3, p: 4, d: "Four generations of a Korean family in Japan, surviving the twentieth century." },
  { t: "Human Acts", a: "Han Kang", g: "Korean, Japanese & East Asian Lit", c: 5, p: 5, d: "The 1980 Gwangju uprising told through the dead and the ones who survived them." },
  { t: "Cursed Bunny", a: "Bora Chung", g: "Korean, Japanese & East Asian Lit", c: 4, p: 4, d: "Korean short stories of capitalist horror, body horror, and folk vengeance." },
  { t: "Midnight Timetable", a: "Bora Chung", g: "Korean, Japanese & East Asian Lit", c: 3, p: 4, d: "A night-shift research institute for things that shouldn't be studied during the day." },
  { t: "The Disaster Tourist", a: "Yun Ko-Eun", g: "Korean, Japanese & East Asian Lit", c: 3, p: 4, d: "A travel agency selling visits to other people's catastrophes." },
  { t: "Hunger", a: "Choi Jin-young", g: "Korean, Japanese & East Asian Lit", c: 4, p: 4, d: "An instant cult classic about appetite, motherhood, and abjection." },
  { t: "Diary of a Murderer", a: "Young-ha Kim", g: "Korean, Japanese & East Asian Lit", c: 3, p: 4, d: "A retired serial killer with dementia chooses his last target." },
  { t: "Mrs. Shim Is a Killer", a: "Kang Jiyoung", g: "Korean, Japanese & East Asian Lit", c: 2, p: 3, d: "A Korean grandmother takes up murder as a hobby." },
  { t: "Lo que sabe la señorita Kim", a: "Cho Nam-joo", g: "Korean, Japanese & East Asian Lit", c: 3, p: 3, d: "Short stories about Korean women from the author of Kim Jiyoung, Born 1982." },
  { t: "The Invisible Hotel", a: "Yeji Y. Ham", g: "Korean, Japanese & East Asian Lit", c: 4, p: 4, d: "A Korean woman dreams every night of a hotel where the dead are stored." },
  { t: "Love in the Big City", a: "Sang Young Park", g: "Korean, Japanese & East Asian Lit", c: 3, p: 4, d: "A queer Korean writer's twenties — love affairs, hangovers, and his ailing mother." },
  { t: "Marigold Mind Laundry", a: "Jungeun Yun", g: "Korean, Japanese & East Asian Lit", c: 2, p: 2, d: "A magical laundromat that washes away unwanted memories in a quiet Korean village." },
  { t: "Molka", a: "Monika Kim", g: "Korean, Japanese & East Asian Lit", c: 3, p: 3, d: "A Korean-American woman discovers spy cams and decides on revenge." },
  { t: "The Eyes Are the Best Part", a: "Monika Kim", g: "Korean, Japanese & East Asian Lit", c: 3, p: 3, d: "A Korean-American daughter develops a very specific appetite for white men's eyes." },
  { t: "Bat Eater and Other Names for Cora Zeng", a: "Kylie Lee Baker", g: "Korean, Japanese & East Asian Lit", c: 3, p: 3, d: "A Chinese-American crime scene cleaner in pandemic NYC starts cleaning crime scenes with patterns." },
  { t: "Japanese Gothic", a: "Kylie Lee Baker", g: "Korean, Japanese & East Asian Lit", c: 3, p: 3, d: "Dual timeline ghost story between modern Japan and the Meiji era." },
  { t: "The Graveyard Apartment", a: "Mariko Koike", g: "Korean, Japanese & East Asian Lit", c: 2, p: 3, d: "A Japanese family moves into an apartment overlooking a crematorium. It does not go well." },
  { t: "Now You're One of Us", a: "Asa Nonami", g: "Korean, Japanese & East Asian Lit", c: 2, p: 3, d: "A young wife discovers her new Japanese family's grotesque secret." },
  { t: "In the Miso Soup", a: "Ryu Murakami", g: "Korean, Japanese & East Asian Lit", c: 3, p: 4, d: "A Tokyo sex-tour guide is hired by an American who is almost certainly a serial killer." },
  { t: "El gato que amaba los libros", a: "Sosuke Natsukawa", g: "Korean, Japanese & East Asian Lit", c: 2, p: 2, d: "A grieving boy and a talking cat go on a quest to free imprisoned books." },
  { t: "Soy un gato", a: "Natsume Soseki", g: "Korean, Japanese & East Asian Lit", c: 4, p: 5, d: "Meiji-era Tokyo satirized by an anonymous, opinionated cat." },
  { t: "What You Are Looking for is in the Library", a: "Michiko Aoyama", g: "Korean, Japanese & East Asian Lit", c: 2, p: 2, d: "A Tokyo librarian recommends a book that changes each visitor's life." },
  { t: "The Hole", a: "Hiroko Oyamada", g: "Korean, Japanese & East Asian Lit", c: 4, p: 4, d: "A new wife in rural Japan falls into a hole that no one else acknowledges." },
  { t: "Taiwan Travelogue", a: "Yáng Shuāng-zǐ", g: "Korean, Japanese & East Asian Lit", c: 4, p: 4, d: "A Japanese novelist tours colonized Taiwan with a young interpreter she falls in love with." },
  { t: "She Is a Haunting", a: "Trang Thanh Tran", g: "Korean, Japanese & East Asian Lit", c: 3, p: 3, d: "A Vietnamese-American teen visits her estranged father in a French colonial house that's eating itself." },
  { t: "Bestiary", a: "K-Ming Chang", g: "Korean, Japanese & East Asian Lit", c: 5, p: 5, d: "Three generations of Taiwanese women, one of whom grows a tiger's tail." },

  // COZY FANTASY
  { t: "The Spellshop", a: "Sarah Beth Durst", g: "Cozy Fantasy", c: 2, p: 2, d: "A reclusive librarian and her sentient spider plant open a spell shop on a small island." },
  { t: "Tea You at the Altar", a: "Rebecca Thorne", g: "Cozy Fantasy", c: 2, p: 2, d: "Cosy fantasy with tea, a tavern, and a sapphic wedding under threat." },
  { t: "The Honey Witch", a: "Sydney J. Shields", g: "Cozy Fantasy", c: 2, p: 2, d: "A young woman accepts her grandmother's witchy island inheritance — including the curse." },
  { t: "The House Witch", a: "Emilie Nikota", g: "Cozy Fantasy", c: 2, p: 2, d: "A castle's secret hearth-witch falls into a slow-burn romance with the king." },
  { t: "A Witch's Guide to Magical Innkeeping", a: "Sangu Mandanna", g: "Cozy Fantasy", c: 2, p: 2, d: "A nearly-burnt-out witch inherits a magical inn and the chaos that comes with it." },
  { t: "The Very Secret Society of Irregular Witches", a: "Sangu Mandanna", g: "Cozy Fantasy", c: 2, p: 2, d: "A lonely witch finds family at a house full of children who shouldn't exist." },
  { t: "A Psalm for the Wild-Built", a: "Becky Chambers", g: "Cozy Fantasy", c: 3, p: 3, s: { name: "Monk and Robot", n: 1, total: 2 }, d: "A tea monk and a curious robot wander a world where humans and machines have been separate for centuries." },
  { t: "Emily Wilde's Encyclopaedia of Faeries", a: "Heather Fawcett", g: "Cozy Fantasy", c: 3, p: 3, s: { name: "Emily Wilde", n: 1, total: 3 }, d: "A prickly academic catalogues faeries from a freezing northern village." },
  { t: "Paladin's Grace", a: "T. Kingfisher", g: "Cozy Fantasy", c: 3, p: 3, s: { name: "The Saint of Steel", n: 1, total: 5 }, d: "A broken paladin and a poison expert solve a murder, slowly fall in love." },
  { t: "Nine Goblins", a: "T. Kingfisher", g: "Cozy Fantasy", c: 2, p: 2, d: "Nine confused goblins lost in elf territory, by the patron saint of cozy weird." },
  { t: "Rewitched", a: "Lucy Jane Wood", g: "Cozy Fantasy", c: 2, p: 2, d: "A witch on the verge of losing her powers must reconnect with her magic and herself." },
  { t: "The Phoenix Keeper", a: "S.A. Maclean", g: "Cozy Fantasy", c: 2, p: 2, d: "A magical zookeeper, an anxious phoenix, and her academic rival." },
  { t: "Dreadful", a: "Caitlin Rozakis", g: "Cozy Fantasy", c: 2, p: 2, d: "A dark wizard wakes up with amnesia and decides being kind might be easier." },
  { t: "The Full Moon Coffee Shop", a: "Mai Mochizuki", g: "Cozy Fantasy", c: 2, p: 2, d: "A Kyoto coffee shop that only appears under a full moon, run by talking cats." },

  // EPIC & DARK FANTASY
  { t: "The Devils", a: "Joe Abercrombie", g: "Epic & Dark Fantasy", c: 3, p: 4, d: "Grimdark epic about an unholy band of monsters sent on a sacred mission." },
  { t: "Babel", a: "R. F. Kuang", g: "Epic & Dark Fantasy", c: 4, p: 4, d: "Translation as colonial violence in an alternate 1830s Oxford." },
  { t: "The Poppy War", a: "R.F. Kuang", g: "Epic & Dark Fantasy", c: 3, p: 4, s: { name: "The Poppy War", n: 1, total: 3 }, d: "A Chinese fantasy epic of war, drugs, and shamanic vengeance." },
  { t: "Jade City", a: "Fonda Lee", g: "Epic & Dark Fantasy", c: 3, p: 4, s: { name: "The Green Bone Saga", n: 1, total: 3 }, d: "Two crime families fight for control of a magical jade trade in a Hong Kong-inspired city." },
  { t: "She Who Became the Sun", a: "Shelley Parker-Chan", g: "Epic & Dark Fantasy", c: 4, p: 4, d: "A peasant girl steals her dead brother's fate and rises through the Mongol-Yuan collapse." },
  { t: "The Spear Cuts Through Water", a: "Simon Jimenez", g: "Epic & Dark Fantasy", c: 5, p: 5, d: "A nested mythic epic about a dying god, two soldiers, and a long journey to the sea." },
  { t: "Tigana", a: "Guy Gavriel Kay", g: "Epic & Dark Fantasy", c: 4, p: 4, d: "A conquered land whose very name has been erased by sorcery — and the rebels trying to remember it." },
  { t: "Under Heaven", a: "Guy Gavriel Kay", g: "Epic & Dark Fantasy", c: 4, p: 4, d: "A man is given 250 horses, a fortune that will get him killed, in Tang-dynasty-inspired empire." },
  { t: "The Sword of Kaigen", a: "M. L. Wang", g: "Epic & Dark Fantasy", c: 3, p: 4, d: "A samurai mother in a remote village faces an empire's collapse." },
  { t: "Blood Over Bright Haven", a: "M. L. Wang", g: "Epic & Dark Fantasy", c: 3, p: 3, d: "An idealistic magical scholar discovers her city's prosperity costs the lives of an entire people." },
  { t: "Piranesi", a: "Susanna Clarke", g: "Epic & Dark Fantasy", c: 4, p: 5, d: "A man lives alone in an endless ocean-filled house. He has only ever known one other person." },
  { t: "Jonathan Strange and Mr Norrell", a: "Susanna Clarke", g: "Epic & Dark Fantasy", c: 5, p: 5, d: "Two magicians revive English magic during the Napoleonic Wars." },
  { t: "The Familiar", a: "Leigh Bardugo", g: "Epic & Dark Fantasy", c: 3, p: 3, d: "A scullion in Golden Age Madrid is forced into the Spanish court's magical proxy war." },
  { t: "The Night Circus", a: "Erin Morgenstern", g: "Epic & Dark Fantasy", c: 3, p: 3, d: "Two magicians bound to a competition that uses an entire travelling circus as the board." },
  { t: "The Starless Sea", a: "Erin Morgenstern", g: "Epic & Dark Fantasy", c: 4, p: 4, d: "A grad student finds a book that contains a story from his own childhood, and follows it underground." },
  { t: "Tress of the Emerald Sea", a: "Brandon Sanderson", g: "Epic & Dark Fantasy", c: 2, p: 2, s: { name: "Secret Projects", n: 1, total: 4 }, d: "A window-washer girl crosses a sea of spores to rescue the boy she loves." },
  { t: "Gideon the Ninth", a: "Tamsyn Muir", g: "Epic & Dark Fantasy", c: 3, p: 4, s: { name: "The Locked Tomb", n: 1, total: 4 }, d: "A sword-swinging lesbian necromancer in space, with jokes." },
  { t: "Red Rising", a: "Pierce Brown", g: "Epic & Dark Fantasy", c: 2, p: 3, s: { name: "Red Rising Saga", n: 1, total: 7 }, d: "A miner on Mars infiltrates the ruling caste through a brutal academy." },
  { t: "The Priory of the Orange Tree", a: "Samantha Shannon", g: "Epic & Dark Fantasy", c: 3, p: 4, s: { name: "The Roots of Chaos", n: 1, total: 2 }, d: "Sapphic dragon epic with court intrigue across multiple continents." },
  { t: "Black Sun", a: "Rebecca Roanhorse", g: "Epic & Dark Fantasy", c: 3, p: 4, s: { name: "Between Earth and Sky", n: 1, total: 3 }, d: "Pre-Columbian-inspired epic of prophecy, sea trade, and a blinded avatar of the crow god." },
  { t: "The City of Brass", a: "S. A. Chakraborty", g: "Epic & Dark Fantasy", c: 3, p: 3, s: { name: "The Daevabad Trilogy", n: 1, total: 3 }, d: "A Cairo street con artist accidentally summons a djinn warrior and is whisked into his city's politics." },
  { t: "Don't Let the Forest In", a: "CG Drews", g: "Epic & Dark Fantasy", c: 2, p: 3, d: "A queer YA gothic about two boys, a haunted boarding school, and the things they draw to life." },
  { t: "The Knight and the Moth", a: "Rachel Gillig", g: "Epic & Dark Fantasy", c: 2, p: 2, d: "A clergy diviner and a sardonic knight on a soft-romantic dark fantasy quest." },
  { t: "Gothikana", a: "RuNyx", g: "Epic & Dark Fantasy", c: 2, p: 2, d: "Dark academia romantasy at a gothic university with secrets." },

  // BODY HORROR & TRANSGRESSIVE
  { t: "Chlorine", a: "Jade Song", g: "Body Horror & Transgressive", c: 3, p: 4, d: "A competitive swimmer becomes a mermaid. Literally and not metaphorically." },
  { t: "Natural Beauty", a: "Ling Ling Huang", g: "Body Horror & Transgressive", c: 3, p: 3, d: "A musician takes a job at a wellness empire that asks more and more of her body." },
  { t: "Immaculate Conception", a: "Ling Ling Huang", g: "Body Horror & Transgressive", c: 3, p: 3, d: "Two artist friends, one of whom is more famous, more talented, and slowly becoming someone else." },
  { t: "Bunny", a: "Mona Awad", g: "Body Horror & Transgressive", c: 4, p: 4, d: "An MFA outsider gets pulled into a coven of cooing rich girls who turn rabbits into boys." },
  { t: "Such Lovely Skin", a: "Tatiana Schlote-Bonne", g: "Body Horror & Transgressive", c: 2, p: 3, d: "A young assistant in publishing notices her body changing in a way no one will explain." },
  { t: "The Unworthy", a: "Agustina Bazterrica", g: "Body Horror & Transgressive", c: 4, p: 4, d: "In a post-collapse convent, a novitiate writes the truth in invisible ink." },
  { t: "Tender Is the Flesh", a: "Agustina Bazterrica", g: "Body Horror & Transgressive", c: 3, p: 4, d: "Meat is illegal, so society farms humans instead." },
  { t: "Pig Tales", a: "Marie Darrieussecq", g: "Body Horror & Transgressive", c: 4, p: 4, d: "A French woman who works in a beauty salon slowly turns into a pig." },
  { t: "Crash", a: "J. G. Ballard", g: "Body Horror & Transgressive", c: 5, p: 5, d: "A subculture of people who find car crashes erotically essential." },
  { t: "Paradise Rot", a: "Jenny Hval", g: "Body Horror & Transgressive", c: 4, p: 4, d: "A Norwegian student in an English share-house full of damp, fruit, and obsession." },
  { t: "Exquisite Corpse", a: "Poppy Z. Brite", g: "Body Horror & Transgressive", c: 4, p: 4, d: "Two gay serial killers in New Orleans find each other." },
  { t: "Zombie", a: "Joyce Carol Oates", g: "Body Horror & Transgressive", c: 4, p: 4, d: "Loosely based on Jeffrey Dahmer, narrated from inside the head." },
  { t: "A Certain Hunger", a: "Chelsea G. Summers", g: "Body Horror & Transgressive", c: 3, p: 3, d: "A food critic recounts her career and her victims from her prison cell." },
  { t: "Cecilia", a: "K-Ming Chang", g: "Body Horror & Transgressive", c: 5, p: 5, d: "An obsessive queer reunion that bends bodies into yearning." },
  { t: "The Piano Teacher", a: "Elfriede Jelinek", g: "Body Horror & Transgressive", c: 5, p: 5, d: "A Vienna piano professor caught between her mother's cruelty and her own self-mutilation." },
  { t: "Monstrilio", a: "Gerardo Sámano Córdova", g: "Body Horror & Transgressive", c: 3, p: 3, d: "A grieving mother grows a creature from a piece of her dead son's lung." },
  { t: "Hijo de Dios", a: "Cormac McCarthy", g: "Body Horror & Transgressive", c: 5, p: 5, d: "Child of God — McCarthy's brief, brutal novel about a man cast out into the dark." },
  { t: "Blood Meridian", a: "Cormac McCarthy", g: "Body Horror & Transgressive", c: 5, p: 5, d: "A scalp-hunting expedition through the 1849 borderlands. Biblical and red." },

  // SOUTHERN & AMERICAN GOTHIC
  { t: "Boys in the Valley", a: "Philip Fracassi", g: "Southern & American Gothic", c: 3, p: 3, d: "A 1900s Pennsylvania orphanage, a possessed boy, and a long winter night." },
  { t: "The Reformatory", a: "Tananarive Due", g: "Southern & American Gothic", c: 3, p: 4, d: "A Black boy is sent to a 1950s Florida reform school where the ghosts outnumber the living." },
  { t: "The Good House", a: "Tananarive Due", g: "Southern & American Gothic", c: 3, p: 3, d: "A grieving mother returns to her grandmother's Washington house, where her son died." },
  { t: "Bastard Out of Carolina", a: "Dorothy Allison", g: "Southern & American Gothic", c: 4, p: 5, d: "A poor white South Carolina girl, her young mother, and her violent stepfather." },
  { t: "Beloved", a: "Toni Morrison", g: "Southern & American Gothic", c: 5, p: 5, d: "A formerly enslaved Ohio woman is visited by the daughter she killed to save." },
  { t: "Bless Me, Ultima", a: "Rudolfo Anaya", g: "Southern & American Gothic", c: 3, p: 4, d: "A New Mexican boy learns the old ways from a curandera in postwar 1940s." },
  { t: "Boy's Life", a: "Robert McCammon", g: "Southern & American Gothic", c: 3, p: 3, d: "A 1964 Alabama boy who witnesses a murder and the strange town that follows." },
  { t: "Sorrowland", a: "Rivers Solomon", g: "Southern & American Gothic", c: 4, p: 4, d: "A Black queer fugitive raises her children in the woods and is changed by what's beneath them." },
  { t: "The Devil All the Time", a: "Donald Ray Pollock", g: "Southern & American Gothic", c: 3, p: 4, d: "Postwar Ohio: a serial killer couple, a psychotic preacher, and the kids caught between them." },
  { t: "Lone Women", a: "Victor LaValle", g: "Southern & American Gothic", c: 3, p: 4, d: "A Black woman homesteads alone in 1915 Montana with a locked steamer trunk." },
  { t: "Ring Shout", a: "P. Djèlí Clark", g: "Southern & American Gothic", c: 3, p: 3, d: "Black women hunt demons disguised as Klansmen in 1920s Macon, Georgia." },
  { t: "The Ballad of Black Tom", a: "Victor LaValle", g: "Southern & American Gothic", c: 3, p: 4, d: "A Harlem hustler's Lovecraft retelling, given back its rage." },
  { t: "When the Reckoning Comes", a: "LaTanya McQueen", g: "Southern & American Gothic", c: 3, p: 3, d: "A Black woman returns to her hometown for a wedding at a former plantation. The dead disagree." },
  { t: "House of Bone and Rain", a: "Gabino Iglesias", g: "Southern & American Gothic", c: 3, p: 3, d: "Five Puerto Rican boys, a hurricane, and a revenge that summons something old." },
  { t: "The Elementals", a: "Michael McDowell", g: "Southern & American Gothic", c: 3, p: 3, d: "Three Victorian houses on an Alabama beach, two families, and the sand-filled third house." },
  { t: "American Rapture", a: "CJ Leede", g: "Southern & American Gothic", c: 3, p: 3, d: "A pandemic of insatiable lust crosses America. A nun walks through it." },
  { t: "I Was a Teenage Slasher", a: "Stephen Graham Jones", g: "Southern & American Gothic", c: 3, p: 3, d: "A Texas 1989 teen becomes the masked killer of his own slasher movie." },
  { t: "Dark Harvest", a: "Norman Partridge", g: "Southern & American Gothic", c: 3, p: 3, d: "A Midwestern town's annual Halloween ritual: hunt the October Boy." },

  // LITERARY FICTION
  { t: "On Earth We're Briefly Gorgeous", a: "Ocean Vuong", g: "Literary Fiction", c: 5, p: 5, d: "A Vietnamese-American son writes a letter to his illiterate mother." },
  { t: "Homegoing", a: "Yaa Gyasi", g: "Literary Fiction", c: 4, p: 5, d: "Two half-sisters in 18th-century Ghana, and seven generations of their descendants on either side of the Atlantic." },
  { t: "The Safekeep", a: "Yael van der Wouden", g: "Literary Fiction", c: 4, p: 4, d: "A reclusive Dutch woman is forced to share her family home with her brother's lover. Postwar history bleeds in." },
  { t: "The Lover", a: "Marguerite Duras", g: "Literary Fiction", c: 5, p: 5, d: "A French teenage girl in colonial Vietnam, an older Chinese lover, and the heat between them." },
  { t: "Things in Nature Merely Grow", a: "Yiyun Li", g: "Literary Fiction", c: 5, p: 5, d: "A mother who has lost both sons writes through it, refusing consolation." },
  { t: "The Secret History", a: "Donna Tartt", g: "Literary Fiction", c: 4, p: 4, d: "A New England classics seminar and the murder its students commit together." },
  { t: "The Shards", a: "Bret Easton Ellis", g: "Literary Fiction", c: 4, p: 4, d: "1981 Los Angeles, an elite high school, and a serial killer who may be Ellis himself." },
  { t: "I Who Have Never Known Men", a: "Jacqueline Harpman", g: "Literary Fiction", c: 4, p: 5, d: "Forty women caged underground escape into a wasteland with no other humans." },
  { t: "Crying in H Mart", a: "Michelle Zauner", g: "Literary Fiction", c: 2, p: 3, d: "Japanese Breakfast's Michelle Zauner on Korean food, grief, and her mother." },
  { t: "Absalom, Absalom!", a: "William Faulkner", g: "Literary Fiction", c: 5, p: 5, d: "A failed Mississippi dynasty, told in spiraling Faulknerian sentences." },
  { t: "The Antidote", a: "Karen Russell", g: "Literary Fiction", c: 4, p: 4, d: "Dust Bowl Nebraska, a 'memory bank' woman who hoards townspeople's worst recollections, and a Black photographer." },
  { t: "How High We Go in the Dark", a: "Sequoia Nagamatsu", g: "Literary Fiction", c: 3, p: 4, d: "Linked stories of an Arctic plague that shapes the next century." },
  { t: "Good Girl", a: "Aria Aber", g: "Literary Fiction", c: 4, p: 4, d: "An Afghan-German teen drifts through Berlin nightlife and an affair with an older writer." },
  { t: "We Are Green and Trembling", a: "Gabriela Cabezón Cámara", g: "Literary Fiction", c: 5, p: 5, d: "Argentine queer historical adventure, lush and lawless." },
  { t: "Caste", a: "Isabel Wilkerson", g: "Literary Fiction", c: 4, p: 4, d: "Nonfiction comparing American racial hierarchy to the caste systems of India and Nazi Germany." },

  // CLASSIC & OLDER GOTHIC
  { t: "Rebecca", a: "Daphne du Maurier", g: "Classic & Older Gothic", c: 3, p: 4, d: "A second wife arrives at Manderley to find the first one has never really left." },
  { t: "Rosemary's Baby", a: "Ira Levin", g: "Classic & Older Gothic", c: 3, p: 3, d: "A young Manhattan wife's pregnancy is going horribly well." },
  { t: "The Stepford Wives", a: "Ira Levin", g: "Classic & Older Gothic", c: 2, p: 3, d: "Levin's brief, lethal feminist parable about a suburb of suspiciously perfect housewives." },
  { t: "The Exorcist", a: "William Peter Blatty", g: "Classic & Older Gothic", c: 3, p: 3, d: "A twelve-year-old in Georgetown begins to speak with another voice." },
  { t: "Los misterios de Udolfo", a: "Ann Radcliffe", g: "Classic & Older Gothic", c: 5, p: 5, d: "The 18th-century gothic novel that taught the genre how to brood." },

  // SCI-FI & SPECULATIVE
  { t: "Dark Matter", a: "Blake Crouch", g: "Sci-Fi & Speculative", c: 2, p: 2, d: "A man wakes up in a life that isn't his, and meets the version of himself who took it." },
  { t: "Recursion", a: "Blake Crouch", g: "Sci-Fi & Speculative", c: 2, p: 3, d: "A technology that lets people relive memories begins erasing entire timelines." },
  { t: "Ubik", a: "Philip K. Dick", g: "Sci-Fi & Speculative", c: 4, p: 4, d: "Reality fractures around a corporate spy team in 1992 Dick-time." },
  { t: "There Is No Antimemetics Division", a: "qntm", g: "Sci-Fi & Speculative", c: 3, p: 4, d: "A bureaucratic agency fights enemies you forget the moment you turn away." },
  { t: "The Memory Police", a: "Yoko Ogawa", g: "Sci-Fi & Speculative", c: 3, p: 4, d: "On an island where objects (and the memory of them) disappear by decree." },
  { t: "Parable of the Sower", a: "Octavia E. Butler", g: "Sci-Fi & Speculative", c: 3, p: 4, s: { name: "Earthseed", n: 1, total: 2 }, d: "A young woman builds a new faith as 2020s America collapses." },
  { t: "The Fifth Season", a: "N.K. Jemisin", g: "Sci-Fi & Speculative", c: 4, p: 5, s: { name: "The Broken Earth", n: 1, total: 3 }, d: "A continent's tectonic apocalypse and the three women living through it." },
  { t: "The Terraformers", a: "Annalee Newitz", g: "Sci-Fi & Speculative", c: 3, p: 3, d: "Sentient flying moose, planetary engineering, and the labor politics of building a world." },
  { t: "Translation State", a: "Ann Leckie", g: "Sci-Fi & Speculative", c: 4, p: 4, d: "Three characters, three first-person voices, navigating a galactic treaty crisis." },

  // PARENTING & MOTHERHOOD
  { t: "Good Inside", a: "Becky Kennedy", g: "Parenting & Motherhood", c: 2, p: 2, d: "Dr. Becky's approach to parenting from a place of believing kids are good underneath." },
  { t: "How to Talk So Kids Will Listen", a: "Adele Faber & Elaine Mazlish", g: "Parenting & Motherhood", c: 2, p: 2, d: "The foundational text on communicating with children." },
  { t: "Tiny Humans, Big Emotions", a: "Alyssa Blask Campbell & Lauren Stauble", g: "Parenting & Motherhood", c: 2, p: 2, d: "Guide to raising emotionally intelligent young children." },
  { t: "The Push", a: "Ashley Audrain", g: "Parenting & Motherhood", c: 2, p: 3, d: "A mother becomes certain her daughter is dangerous. Her husband believes otherwise." },
  { t: "The School for Good Mothers", a: "Jessamine Chan", g: "Parenting & Motherhood", c: 3, p: 3, d: "A government program retrains 'bad' mothers using lifelike robot children." },
  { t: "Nightbitch", a: "Rachel Yoder", g: "Parenting & Motherhood", c: 3, p: 3, d: "A new mother becomes increasingly certain she is turning into a dog." }
];
