// AUTO-GENERATED by scripts/build-share-cards.mjs.
// Per-frame content-safe opening box (px @1080x1350). Frames vary, so each slug
// carries its own box; the DOM card and the render function both use it.
export const DEFAULT_BOX = { x: 291, y: 256, w: 485, h: 782 };
export const CARD_BOXES = {
  "adventure": { x: 286, y: 213, w: 506, h: 853 },
  "comedy": { x: 265, y: 270, w: 550, h: 810 },
  "crime": { x: 285, y: 245, w: 509, h: 750 },
  "fantasy": { x: 299, y: 241, w: 482, h: 786 },
  "generic": { x: 330, y: 305, w: 418, h: 677 },
  "gothic": { x: 291, y: 256, w: 485, h: 782 },
  "horror": { x: 287, y: 221, w: 507, h: 795 },
  "ideas": { x: 309, y: 256, w: 460, h: 734 },
  "literary": { x: 286, y: 272, w: 508, h: 795 },
  "moment-book": { x: 309, y: 255, w: 460, h: 760 },
  "moment-goal": { x: 310, y: 263, w: 459, h: 775 },
  "moment-milestone": { x: 330, y: 305, w: 418, h: 677 },
  "moment-plan": { x: 270, y: 204, w: 538, h: 844 },
  "moment-series": { x: 324, y: 295, w: 432, h: 725 },
  "myth": { x: 288, y: 230, w: 503, h: 818 },
  "panel": { x: 307, y: 288, w: 465, h: 716 },
  "place": { x: 268, y: 238, w: 543, h: 808 },
  "romance": { x: 339, y: 281, w: 400, h: 724 },
  "scifi": { x: 315, y: 278, w: 449, h: 744 },
  "society": { x: 302, y: 333, w: 475, h: 664 },
  "verse": { x: 293, y: 240, w: 493, h: 751 },
  "young": { x: 297, y: 244, w: 485, h: 808 },
};
