// AUTO-GENERATED by scripts/build-share-cards.mjs.
// Normalized slugs (genres + moment-*) that have their framed card assets ready.
// The app shows the framed card only for these; others fall back to the cover card.
export const CARD_GENRES = [
  "adventure",
  "comedy",
  "crime",
  "fantasy",
  "generic",
  "gothic",
  "horror",
  "ideas",
  "literary",
  "moment-book",
  "moment-goal",
  "moment-milestone",
  "moment-plan",
  "moment-series",
  "myth",
  "panel",
  "place",
  "romance",
  "scifi",
  "society",
  "verse",
  "young",
];
