// AUTO-GENERATED by the share-card prep script.
// Normalized slugs that have a framed card asset pair (frame.png + art-trim.png).
// The app shows the framed art card only for these; others keep the cover card.
export const CARD_GENRES = [
  "classicoldergothic",
];
