// src/lib/genreDescriptions.js
//
// Per-genre sub-line for framed genre share cards (genre_count / new_genre).
// Keyed by canonical Oracle genre name (matches public/cards/<genre>/ folders).
// momentCopy() falls back to the generic i18n sub when a genre is absent here.

export const GENRE_DESCRIPTIONS = {
  'African Literary Fiction': 'Where memory, land, and voice refuse to be silenced.',
  'American Gothic': 'Old sins keep their addresses in the new world.',
  'Apocalyptic Fantasy': 'At the end of everything, a story still burns.',
  'Arthurian Retelling': 'The old crown is passed to newer, sharper hands.',
  'Arthurian-Inspired': 'Round tables, older bargains, and swords that remember.',
  'Body Horror & Transgressive': 'The flesh keeps its own unspeakable diary.',
  'British & Rural Horror': 'Something ancient stirs beneath the quiet hedgerows.',
  'Children\'s Picture Book': 'Small pages that hold the whole wide world.',
  'Classic & Older Gothic': 'The house remembers every reader who dares its halls.',
  'Classics': 'The voices that time refused to let fade.',
  'Comedy & Wit': 'Read for the sheer, sharp joy of it.',
  'Coming of Age': 'The long, luminous walk toward becoming yourself.',
  'Contemporary Fantasy': 'Magic hiding in plain, modern sight.',
  'Contemporary Fiction': 'The present, rendered in aching, ordinary detail.',
  'Cozy Fantasy': 'Small magics, warm hearths, and gentle quests.',
  'Cozy Mystery': 'A quiet town, a tidy crime, a very sharp mind.',
  'Cyberpunk': 'Neon, wire, and the fight for a soul in the machine.',
  'Dark Fantasy': 'Where the wonder wears teeth.',
  'East Asian Lit': 'Quiet precision, deep water, and the weight of the unsaid.',
  'Epic & Dark Fantasy': 'Vast worlds, long shadows, and the price of the throne.',
  'Epic Fantasy': 'Kingdoms rise and fall across the turning of pages.',
  'Epic Poetry': 'The oldest music of heroes and the gods.',
  'Experimental & Avant-Garde': 'The form itself becomes the frontier.',
  'Fairy Tale Retelling': 'The old stories, told again with the teeth left in.',
  'Fantasy': 'Every door in these pages opens onto wonder.',
  'Fantasy Romance': 'Two hearts against a world of magic.',
  'Feminist & Social Commentary': 'The sharp pages that named what needed naming.',
  'Feminist Gothic': 'The madwoman was never the one to fear.',
  'Folk Horror': 'The old ways were never truly buried.',
  'Gothic': 'Beauty, dread, and the ruin that outlives us.',
  'Gothic & Haunted Houses': 'Every locked room keeps its patient secret.',
  'Graphic Novel': 'Where the picture and the word conspire.',
  'Historical': 'The past, walked in living footsteps.',
  'Historical Biography': 'One real life, held up to the light.',
  'Historical Fiction': 'History given breath, pulse, and a beating heart.',
  'Historical Romance': 'Love letters across the long century.',
  'Horror': 'The pages you read with the lights left on.',
  'Indigenous Fiction': 'Stories rooted deep, older than the maps.',
  'Intimate Fiction': 'The small, close rooms of the human heart.',
  'Irish Folklore': 'The good folk are listening at the door.',
  'Italian Gothic': 'Old villas keep their velvet, and their ghosts.',
  'Japanese & East Asian Horror': 'The quiet dread that waits behind the screen.',
  'Japanese & East Asian Lit': 'Stillness, season, and the ache beneath the surface.',
  'Japanese Lit': 'Precise, patient, and quietly devastating.',
  'Korean, Japanese & East Asian Lit': 'Sharp modern voices from the far east of the page.',
  'LGBTQ+ Romance': 'Love, told at last in its own true name.',
  'Latin American Horror & Literary': 'Where the marvelous and the monstrous share a house.',
  'Latin American Literary': 'History, myth, and heat pressed into prose.',
  'Literary Fiction': 'The sentences you underline and never forget.',
  'Magical Realism': 'The impossible, worn like an everyday coat.',
  'Malaysian Literary Fiction': 'Monsoon, memory, and many-tongued streets.',
  'Martial Arts': 'Discipline, honor, and the poetry of the blade.',
  'Medieval': 'Mud, faith, and iron under a low grey sky.',
  'Memoir': 'One true life, offered onto the page.',
  'Monster Horror': 'Something enormous is awake and hungry.',
  'Mystery': 'Every clue a thread, every page a tightening.',
  'Mythological Fantasy': 'The gods still walk when the story calls them.',
  'Non-Fiction': 'The true world, told with a storyteller\'s craft.',
  'Parenting & Motherhood': 'The fierce, unglamorous work of love.',
  'Philosophical Fiction': 'Stories that argue with the meaning of things.',
  'Political Fiction': 'Power on the page, and who it costs.',
  'Psychological Fiction': 'The mind is the darkest room of all.',
  'Romance': 'The pages that make the heart insist.',
  'Romantasy': 'Where the spellbook and the love story share a spine.',
  'Romantic Fantasy': 'Enchantment, longing, and a world worth saving.',
  'Sapphic & Feminist Gothic': 'Two women, one haunted house, endless secrets.',
  'Sapphic Fantasy': 'Her heart, her sword, and a world of her own making.',
  'Sci-Fi & Speculative': 'The what-ifs that light the road ahead.',
  'Scientific Anthropology': 'The long, strange story of being human.',
  'Scottish': 'Heather, stone, and the long memory of the glen.',
  'Slasher': 'Count the pages. Count who\'s left.',
  'Slavic Folk Horror': 'The forest keeps its old and hungry gods.',
  'Smutty Corner': 'Unashamed, unhurried, and utterly yours.',
  'Social Commentary & History': 'The record of how we lived, and failed, and hoped.',
  'Southern & American Gothic': 'Heat, secrets, and the rot beneath the porch.',
  'Spanish Literary': 'Sun, sorrow, and the long shadow of the past.',
  'Superhero Epic': 'Ordinary hearts, extraordinary weight.',
  'Supernatural Horror': 'The veil is thin, and something leans through.',
  'Transgressive & Body Horror': 'The page that dares you to keep reading.',
  'Urban Fantasy': 'Magic runs the back alleys of the city.',
  'Vampires': 'Immortal, ravenous, and impossibly charming.',
  'Witches': 'The old power, gathered and reclaimed.',
  'Zombies': 'The dead walk, and the living must choose.',
};
