// AUTO-GENERATED from the genre catalog. name -> { slug, sub }.
// slug = folder under public/cards/<slug>/ ; sub = card sub-line (English).
export const GENRE_CARD_META = {
  'Fantasy': { slug: 'fantasy', sub: 'Magic, invented worlds, and the impossible made rule-bound.' },
  'Fairy Tale Retelling': { slug: 'fairytaleretelling', sub: 'Familiar stories cracked open and rebuilt.' },
  'Martial Arts': { slug: 'martialarts', sub: 'Discipline, combat, and the body as instrument.' },
  'Contemporary Fiction': { slug: 'contemporaryfiction', sub: 'Life as it\'s lived right now.' },
  'Sapphic Fantasy': { slug: 'sapphicfantasy', sub: 'Queer women at the center of invented worlds — the romance, the magic, and the stakes all treated as equally real.' },
  'Historical Romance': { slug: 'historicalromance', sub: 'A love story set firmly in another era, where the constraints of the period — propriety, class, arranged marriage — become the very thing the romance has to overcome.' },
  'Epic Poetry': { slug: 'epicpoetry', sub: 'Verse built for scale — gods, wars, and journeys sustained across thousands of lines.' },
  'Graphic Novel': { slug: 'graphicnovel', sub: 'Stories told through sequential art and illustration — from superhero sagas to literary memoirs.' },
  'Japanese & East Asian Horror': { slug: 'japaneseeastasianhorror', sub: 'Grudges that outlast death.' },
  'Intimate Fiction': { slug: 'intimatefiction', sub: 'Stories where desire is central, not incidental.' },
  'Philosophical Fiction': { slug: 'philosophicalfiction', sub: 'Novels that want to think.' },
  'Slasher': { slug: 'slasher', sub: 'The knife, the mask, the body count.' },
  'Sci-Fi & Speculative': { slug: 'scifispeculative', sub: 'Stars, time, and the estrangement of the possible.' },
  'Witches': { slug: 'witches', sub: 'Cunning women, herbalists, sabbaths, and the persecution of the different.' },
  'Cozy Fantasy': { slug: 'cozyfantasy', sub: 'Enchantment with a hearth at its center.' },
  'Experimental & Avant-Garde': { slug: 'experimentalavantgarde', sub: 'Fiction that breaks the frame.' },
  'Vampires': { slug: 'vampires', sub: 'The blood-drinker across centuries — from Varney and Carmilla to Rice\'s chronicles.' },
  'Gothic & Haunted Houses': { slug: 'gothichauntedhouses', sub: 'Spirits inhabit the architecture.' },
  'Magical Realism': { slug: 'magicalrealism', sub: 'The miraculous woven into the everyday without apology or explanation.' },
  'Coming of Age': { slug: 'comingofage', sub: 'The crossing from one version of yourself to another.' },
  'Mythological Fantasy': { slug: 'mythologicalfantasy', sub: 'Gods walk among us, or used to.' },
  'Smutty Corner': { slug: 'smuttycorner', sub: 'Explicit, unapologetic, and here for it.' },
  'Classics': { slug: 'classics', sub: 'The books that refused to stay in their century.' },
  'Comedy & Wit': { slug: 'comedywit', sub: 'Sharp tongues, absurd situations, and the quiet joy of a book that makes you laugh out loud.' },
  'Literary Fiction': { slug: 'literaryfiction', sub: 'The work that resists easy genre — the novel as art object.' },
  'Superhero Epic': { slug: 'superheroepic', sub: 'Capes, powers, and the weight of being extraordinary.' },
  'Folk Horror': { slug: 'folkhorror', sub: 'Rooted in the land, the old ways, and the community that keeps terrible secrets.' },
  'Fantasy Romance': { slug: 'fantasyromance', sub: 'Romance and magic intertwined, neither diminishing the other.' },
  'Social Commentary': { slug: 'socialcommentary', sub: 'Fiction with an argument.' },
  'Mystery': { slug: 'mystery', sub: 'Something is wrong, and someone needs to figure out what.' },
  'Biography': { slug: 'biography', sub: 'A life examined and reconstructed.' },
  'Feminist & Sapphic Gothic': { slug: 'feministsapphicgothic', sub: 'The feminine gaze turned inward and outward on a world that haunts women in particular ways.' },
  'East Asian Literary Fiction': { slug: 'eastasianliteraryfiction', sub: 'The literary traditions of Japan, Korea, China, and their neighbors — novels of alienation, obligation, and quiet devastation.' },
  'Romance': { slug: 'romance', sub: 'Love at the center of the plot, and the promise of an ending that earns it.' },
  'Dark & Epic Fantasy': { slug: 'darkepicfantasy', sub: 'Dragons, war, chosen ones, and the cost of power across vast invented worlds.' },
  'International Fiction': { slug: 'internationalfiction', sub: 'Literary fiction rooted in specific places and traditions outside the Anglo-American mainstream — African, Latin American, Celtic, and beyond.' },
  'Southern & American Gothic': { slug: 'southernamericangothic', sub: 'Kudzu on the verandah, rot beneath the gentility, violence encoded in the landscape.' },
  'Classic & Older Gothic': { slug: 'classicoldergothic', sub: 'The original haunted manor, the brooding aristocrat, the ancestral curse.' },
  'Arthurian': { slug: 'arthurian', sub: 'Camelot\'s endless retelling — Merlin\'s prophecies, the Round Table\'s fractures, Guinevere and Lancelot\'s impossible love.' },
  'Body Horror & Transgressive': { slug: 'bodyhorrortransgressive', sub: 'Where the body becomes the site of horror.' },
  'Parenting & Motherhood': { slug: 'parentingmotherhood', sub: 'The self before and after.' },
  'Historical Fiction': { slug: 'historicalfiction', sub: 'Novels that plant you firmly in another era.' },
  'Children\'s Picture Book': { slug: 'childrenspicturebook', sub: 'Stories built for young eyes encountering the world for the first time.' },
  'LGBTQ+ Romance': { slug: 'lgbtqromance', sub: 'Love stories where desire doesn\'t conform to the default.' },
  'Zombies': { slug: 'zombies', sub: 'The dead who keep moving.' },
  'Cyberpunk': { slug: 'cyberpunk', sub: 'Neon rain and corporate dystopia.' },
  'Horror': { slug: 'horror', sub: 'Dread in its purest form — the thing in the dark, the wrongness beneath the ordinary, the fear that lingers after the last page.' },
  'Non-Fiction': { slug: 'nonfiction', sub: 'The world as it actually is, examined with the same rigor and care good fiction demands.' },
  'Psychological Fiction': { slug: 'psychologicalfiction', sub: 'The interior as the true battleground.' },
};
