// seriesEditorialSql.mjs — turn _shared/seriesEditorial.mjs into a migration.
//
//   node batch-scripts/manual/seriesEditorialSql.mjs > supabase/migrations/<ts>_series_editorial_descriptions.sql
//
// Emits SQL rather than writing to the database so the text is reviewed in a
// diff and applied from the repo like every other migration (SECURITY_AUDIT
// H2: no dashboard edits to load-bearing SEO data).
//
// Overwrites only placeholders: a NULL description, or one whose source is
// 'composed' or 'wikipedia'. A description with a NULL source is treated as
// hand-written and left alone (see 20260910000000); so is 'manual'. Rows are
// stamped 'oracle' — the column's label for LLM-written text — because that is
// what this is, reviewed or not. Change to 'manual' after editing one by hand.

import { SERIES_EDITORIAL } from '../_shared/seriesEditorial.mjs';

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const out = [];
out.push(`-- Series editorial descriptions — generated by batch-scripts/manual/seriesEditorialSql.mjs`);
out.push(`-- from batch-scripts/_shared/seriesEditorial.mjs. Edit the data file and regenerate;`);
out.push(`-- do not hand-edit this file.`);
out.push('');
out.push('begin;');
out.push('');
for (const { name, description } of SERIES_EDITORIAL) {
  out.push(`update public.series`);
  out.push(`   set description = ${q(description)},`);
  out.push(`       description_source = 'oracle'`);
  out.push(` where normalized_name = public.normalize_series_name(${q(name)})`);
  out.push(`   and (description is null or description_source in ('composed', 'wikipedia'));`);
  out.push('');
}
out.push('commit;');
out.push('');
out.push('-- Verification: every name should resolve to exactly one series row.');
out.push('-- A row with n = 0 means the catalog spells the series differently; fix the');
out.push('-- name in seriesEditorial.mjs and regenerate.');
out.push('--');
out.push('--   select v.name, count(s.id) as n, max(s.description_source) as source');
out.push('--     from (values');
out.push(SERIES_EDITORIAL.map((s, i) => `--       (${q(s.name)})${i < SERIES_EDITORIAL.length - 1 ? ',' : ''}`).join('\n'));
out.push('--     ) as v(name)');
out.push('--     left join public.series s on s.normalized_name = public.normalize_series_name(v.name)');
out.push('--    group by v.name order by n, v.name;');
process.stdout.write(out.join('\n') + '\n');
