-- v0.73 — Oracle readings (Pro extras). 2026-09-25.
-- Spec: docs/pro-tier-v1-spec.md §6 · Client: src/lib/oracleReadings.js
--
-- Long-form Oracle output worth keeping:
--   why_long    — "Why this book, for you", one per (reader, book, language)
--   taste_chart — "Your reader's chart", one per (reader, language)
--
-- The Oracle call itself is gated and metered in claude.js (Pro-only sources);
-- this table only remembers the answer so it is not paid for twice.
--
-- Idempotent.

create table if not exists public.oracle_readings (
  id          bigint generated by default as identity primary key,
  user_id     uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  kind        text        not null,
  subject_key text        not null default '',
  lang        text        not null default 'en',
  body        jsonb       not null,
  created_at  timestamptz not null default now(),
  constraint oracle_readings_kind_check check (kind in ('why_long', 'taste_chart')),
  constraint oracle_readings_lang_check check (lang in ('en', 'es')),
  -- A reading is a few paragraphs. Anything much larger is a bug or abuse.
  constraint oracle_readings_body_size check (pg_column_size(body) < 16384),
  constraint oracle_readings_one_per_subject unique (user_id, kind, subject_key, lang)
);

comment on table public.oracle_readings is
  'v0.73: cached long-form Oracle readings (why_long per book, taste_chart per reader). Private to the reader.';

alter table public.oracle_readings enable row level security;

drop policy if exists "Own readings" on public.oracle_readings;
create policy "Own readings" on public.oracle_readings
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

revoke all on public.oracle_readings from anon;
grant select, insert, update, delete on public.oracle_readings to authenticated;

do $$ begin
  raise notice 'v0.73: oracle_readings ready.';
end $$;
