-- Descriptions for the genres the Oracle invented.
--
-- The taxonomy grew from 15 seeds to 142 as nightly curation created genres it
-- needed, and none of the new ones arrived with a description — 93 of 142 were
-- blank. A genre with no description is a bare name in the picker, which makes
-- it hard to choose between "Dark Fantasy" and "Grimdark", and it leaves the
-- genre browser looking unfinished exactly where it is growing fastest.
--
-- Authored in scripts/genre-descriptions-data.mjs and generated by
-- scripts/build-genre-descriptions.mjs — edit there, not here. The same source
-- produces the short card sub-lines in src/lib/genreDescriptions.js, so the
-- picker and the share card can never disagree.
--
-- SAFE TO RE-RUN. Only rows with a NULL or empty description are touched, so
-- anything edited by hand in Supabase survives.

update public.genres g
set description = v.description
from (values
  ('Adventure', 'Somewhere to go and trouble on the way. Movement as the engine of the story — journeys, pursuits, and narrow escapes, told for the pleasure of not knowing what is around the bend.'),
  ('Alien Invasion', 'They arrived, and they did not come to talk. Occupation, resistance and survival after something arrives from elsewhere with plans of its own.'),
  ('American Gothic', 'Old sins keep their addresses in the new world. Decay and inherited guilt in an American register — small towns, family land, and the violence underneath the founding story.'),
  ('American Literature', 'A country arguing with itself on the page. The American literary tradition — frontier and city, immigration and inheritance, and the promise examined against the record.'),
  ('Apocalyptic', 'The end, while it is still happening. Fiction set during the collapse rather than after it — the last weeks, the failing institutions, the decisions made too late.'),
  ('Art History', 'Objects, and the centuries around them. How images and artefacts were made, seen and argued over — from patronage and technique to what a period wanted from its art.'),
  ('Asian-inspired Fantasy', 'Invented worlds drawn from Asian myth and history. Courts, cultivation, spirits and dynastic intrigue, built on traditions the Western fantasy shelf spent a century ignoring.'),
  ('Australian Gothic', 'The bush swallows people and keeps quiet about it. Gothic transplanted to a continent that will not cooperate — heat, distance, and a colonial history that refuses to stay buried.'),
  ('Aviation', 'Weather, machinery, and the ground a long way down. Flight in fact and fiction — pilots, aircraft, and the narrow tolerances that keep both in the air.'),
  ('Celtic Fantasy', 'The old country, where the hills are hollow. Fae bargains, standing stones and the thin places between worlds, rooted in Irish, Scottish and Welsh tradition.'),
  ('Chicano & Latinx Fiction', 'Two languages, one shelf, no apology. Chicano and Latinx writing in the United States — borderlands, code-switching, and the argument over who counts as American.'),
  ('Children''s Fiction', 'Built for readers who are still arriving. Chapter books and middle-grade novels — plain-spoken, unhurried with feeling, and far more serious than adults remember.'),
  ('Classic Literary Fiction', 'The novels that set the terms. The literary canon before the modern period — books still argued with, whether or not they are still loved.'),
  ('Classic Science Fiction', 'The genre when it was still deciding what it was. The pulp-to-New-Wave canon — Asimov, Clarke, Le Guin, Butler — where the ideas that everything since is answering were first set down.'),
  ('Cli-Fi & Eco-Fiction', 'The weather stopped being background. Fiction that takes climate and ecological collapse as its subject — near-future, present-tense, and increasingly not speculative.'),
  ('Cosmic Horror', 'The universe is indifferent, and you have just noticed. Horror of scale and insignificance — vast intelligences, unbearable knowledge, and a cosmos with no interest in human survival.'),
  ('Court Intrigue', 'The knife is in the compliment. Power contested in throne rooms and drawing rooms, where alliance, marriage and rumour do the work of armies.'),
  ('Crime Fiction', 'The act, and everyone it touches. Fiction organised around crime — as often about the people surrounding it as the person who did it.'),
  ('Crime Noir', 'Everyone is compromised, including the narrator. Fatalism, moral murk and rain-slick cities — the strand of crime writing where the detective is part of the problem.'),
  ('Cult Fiction', 'Never a bestseller; never out of print. Books that found a devoted readership rather than a wide one, and kept it for decades.'),
  ('Cultural Studies', 'The ordinary, read closely. Analysis of culture as it is actually lived — media, subcultures and the meanings carried by everyday things.'),
  ('Dark Academia', 'Old libraries, worse friendships. Cloistered institutions, obsessive study and a group of students who take something much too far.'),
  ('Dark Fantasy', 'Magic that costs more than it gives. Fantasy written in the register of horror — dread, moral rot and worlds where the supernatural is a threat rather than a wonder.'),
  ('Demons & Monsters', 'Something with intent, and teeth. Possession, summoning and the monstrous made physical — horror where the threat has a shape you can name.'),
  ('Dragons', 'The oldest thing in the sky. Hoards, riddles, bonded riders and the long shadow a dragon casts over whatever kingdom is unlucky enough to have one.'),
  ('Drama', 'Written to be spoken aloud. Plays and dramatic writing — character revealed through dialogue and staging rather than narration.'),
  ('Dying Earth', 'The sun is going out and everyone has adjusted. Fantasy set at the exhausted end of time, where magic is the residue of forgotten science and decline is simply the weather.'),
  ('Dystopian', 'The system works exactly as intended. Societies organised around a single terrible principle, seen from the inside by someone beginning to notice.'),
  ('Eco-Fiction', 'The land is a character and it is not well. Writing rooted in landscape and ecology, where the relationship between people and place carries the story.'),
  ('Epic Fantasy', 'Invented worlds with maps, and wars worth the map. Long-form fantasy at scale — many viewpoints, contested kingdoms, and a plot that takes several volumes to turn over.'),
  ('Epistolary Fiction', 'Told in letters, and in what the letters avoid. Novels assembled from documents — correspondence, diaries, transcripts — where the gaps carry as much as the text.'),
  ('Espionage', 'Loyalty is a working hypothesis. Tradecraft, handlers and betrayal — fiction where the enemy is often on your own side of the desk.'),
  ('Existential', 'The question of why to continue, taken seriously. Fiction concerned with meaning, freedom and absurdity — usually more interested in the asking than in any answer.'),
  ('Family Drama', 'The people you cannot resign from. Fiction about inheritance, obligation and long-running injury within a family, across a generation or several.'),
  ('Feminist Fiction', 'Written with the assumption that women are the subject. Fiction that takes women''s interiority, labour and constraint as its central material rather than its backdrop.'),
  ('First Contact', 'Something answered. The moment humanity meets another intelligence, and the far harder problem of understanding it.'),
  ('Flintlock Fantasy', 'Muskets, revolutions, and magic that has not read the manual. Fantasy set in the age of gunpowder and upheaval, where sorcery has to share the field with drill and artillery.'),
  ('Folklore', 'The stories that were told before anyone wrote them down. Tales, superstitions and oral tradition — collected, retold, and still doing the work they were made for.'),
  ('Grief Memoir', 'Writing from inside the loss. First-person accounts of bereavement — the disordered months, the practicalities, and the long revision of a life around an absence.'),
  ('Grimdark', 'Nobody is coming to save the village. Fantasy stripped of consolation — morally compromised characters, violence with consequences, and heroism treated as a suspicious claim.'),
  ('Haunted Houses', 'The house keeps its own tenants. Architecture as antagonist — the room that is colder, the corridor that is longer at night, the family that will not leave.'),
  ('Heist', 'A plan, a crew, and the part that goes wrong. The job assembled, rehearsed and improvised through — pleasure taken in competence and in its failure.'),
  ('Historical Fantasy', 'The past, with the magic left in. Real periods and real cities where the supernatural is simply part of the record, and history bends around it.'),
  ('Identity & Belonging', 'Where you are from, and whether it will have you. Fiction about diaspora, assimilation and the negotiation between the self you were given and the one you are building.'),
  ('Illustrated', 'The pictures are not decoration. Books where image and text carry the meaning together — art books, illustrated editions and visual essays.'),
  ('Indigenous Horror', 'The land remembers what was done on it. Horror grounded in Indigenous traditions and histories, where colonial violence is not backstory but the thing in the room.'),
  ('Inspirational', 'Written to be of use. Books offered as encouragement — faith, resilience and recovery, aimed squarely at the reader''s own life.'),
  ('Irish Fiction', 'Small country, disproportionate quantity of sentences. The Irish literary tradition — language pushed hard, family and emigration, and comedy sitting flush against grief.'),
  ('Japanese & East Asian Literary Fiction', 'Restraint, obligation, and the thing left unsaid. The literary traditions of Japan, Korea and China — quiet devastation, formal control, and alienation rendered precisely.'),
  ('Legal Thriller', 'Justice, argued procedurally. Courtrooms, discovery and the gap between what is true and what can be proven.'),
  ('LGBTQ+ Fiction', 'Lives lived outside the default, on their own terms. Queer fiction across every genre — coming out and long after, chosen family, and stories where being queer is simply the given.'),
  ('Literary Criticism', 'Reading, taken seriously as work. Essays and scholarship on how books do what they do, and what they are doing when they do it.'),
  ('LitRPG', 'The world has stats, and so do you. Fiction that runs on game mechanics — levels, classes and quest logs treated as physics rather than metaphor.'),
  ('Medical Narrative', 'The body as case, and as person. Writing from clinics and sickbeds — doctors, patients and the gap between a diagnosis and what it means to live with one.'),
  ('Memoir', 'One life, told by the person inside it. A remembered life rather than a documented one — shaped, selective, and answerable to feeling as much as to fact.'),
  ('Metafiction', 'The author is in the room and will not leave. Stories about storytelling — footnotes, false documents and narrators who address the person reading them.'),
  ('Military Fantasy', 'Logistics, drill, and sorcery on the order of battle. Invented worlds seen from inside the ranks, where campaigns are won by supply lines as often as by spellcraft.'),
  ('Military Science Fiction', 'The future, seen from inside the ranks. Combat, command and the machinery of war among the stars, usually more interested in soldiers than in admirals.'),
  ('Modernist', 'The sentence stopped behaving. Early twentieth-century fiction that broke narrative open — interiority, fragmentation, and form as argument.'),
  ('Music Fiction', 'Bands, records, and the noise in between. Fiction about making and loving music — scenes, tours, and the particular way a song attaches to a life.'),
  ('Paranormal', 'The world has more residents than you were told. Ghosts, psychics and the unexplained treated as fact — the supernatural as a fixture of the world rather than an intrusion into it.'),
  ('Philosophy', 'The questions that refuse to resolve. Ethics, mind, knowledge and being — primary texts and the writing that makes them approachable.'),
  ('Political Fiction', 'Power, and who pays for it. Fiction about the machinery of governance and its human cost — written from inside the argument, not above it.'),
  ('Portal Fantasy', 'A door that should not have been there. Someone crosses from our world into another and has to learn its rules — and decide, eventually, whether to go back.'),
  ('Post-Apocalyptic', 'After the end, the long business of continuing. Survival, scavenging and the slow reassembly of something like a society in the ruins of the old one.'),
  ('Postmodern', 'The novel, aware it is a novel. Fiction that plays with its own machinery — unreliable structure, nested stories, and a deep suspicion of the straight line.'),
  ('Quest Fantasy', 'A road, a company, and something that must be carried. The journey structure at its most deliberate: an object to deliver or destroy, and a party changed by the walking.'),
  ('Romantic Fiction', 'Two people, and everything in the way. Love as the central concern, told across any setting — the obstacle matters less than the pull.'),
  ('Satire', 'A joke with a target. Comedy aimed at institutions and pieties — funny because it is accurate, and uncomfortable for the same reason.'),
  ('Satirical Fiction', 'The world exaggerated just enough to be recognised. Novels that push a real absurdity one step further and let it do the arguing.'),
  ('Scandinavian Horror', 'Long dark, deep forest, small town. Nordic horror — isolation, folklore and the particular dread of a landscape that can simply absorb a person.'),
  ('Science Fiction', 'The future, argued rather than assumed. Fiction that changes one thing about the world and follows the consequences honestly, from hard extrapolation to social thought experiment.'),
  ('Short Fiction', 'The whole thing, in one sitting. Stories and collections built for compression, where nothing is allowed to be merely furniture.'),
  ('Southern Gothic', 'Heat, family, and rot beneath the gentility. The American South as gothic landscape — grand houses in decline, secrets kept for generations, and grotesquerie treated as ordinary.'),
  ('Space Opera', 'Empires, fleets, and a very large map. Interstellar fiction at full scale — dynasties, wars and long journeys, told with more appetite for spectacle than for engineering.'),
  ('Spanish Literature', 'Written in Spanish, and not translated into blandness. The literature of Spain and the Spanish language — from the Golden Age through the contemporary novel.'),
  ('Speculative Fiction', 'One rule changed, everything else honest. The broad church between science fiction and literary fiction — books that ask "what if" without needing a spaceship to do it.'),
  ('Sports Fiction', 'The body, the clock, the margin. Competition as subject — discipline, failure and the private arithmetic of getting better at something.'),
  ('Steampunk', 'Brass, steam, and a century that never happened. Retrofuturism built on Victorian machinery — airships, automata and industry running on rules of its own.'),
  ('Supernatural', 'The rules bend, and nobody explains why. Fiction where forces beyond the natural order act on the story, whether or not anyone in it understands them.'),
  ('Surrealism', 'Dream logic, followed rigorously. Fiction that abandons realist causality without abandoning consequence — the impossible treated with a straight face.'),
  ('Suspense', 'You know what is coming; that is the point. Dread built from anticipation rather than surprise — the reader holds information the characters do not.'),
  ('Techno-Horror', 'The machine is doing something it was not asked to. Horror from technology itself — systems that exceed their brief, networks that watch back, and bodies interfaced with the wrong thing.'),
  ('Theology', 'Belief, examined with rigour. Religious thought and scholarship — doctrine, scripture and the long argument about what any of it obliges.'),
  ('Thriller', 'The clock is running and it is not on your side. Pace as the organising principle — escalating stakes, tightening constraints, and a threat that keeps moving.'),
  ('Time Travel', 'The same moment, approached from the wrong direction. Loops, paradoxes and altered pasts — stories where causality is the antagonist.'),
  ('Urban Fantasy', 'Wards on the fire escape, something old in the subway. Magic operating inside the modern city — hidden courts, working practitioners, and a supernatural underworld with its own politics.'),
  ('Victorian Fiction', 'Three volumes, and a great deal left unsaid. The nineteenth-century novel — serialised, socially exacting, and far stranger than its reputation.'),
  ('Vikings & Norse', 'Longships, oaths, and the winter at the end of the world. Sagas and Norse-rooted fiction — feud and kinship, seiðr and prophecy, and gods who are no help at all.'),
  ('War Fiction', 'What it was actually like, insofar as that can be written. Combat and its long aftermath — the soldier''s war, the civilian''s war, and the decades that follow both.'),
  ('Werewolves', 'The moon, and what it makes of you. Transformation as horror and as freedom — the body that changes, and the appetite that comes with it.'),
  ('Western', 'Open country, and law arriving late. The frontier and its myths — and, increasingly, the books written to take those myths apart.'),
  ('Young Adult', 'First everything, at full volume. Fiction written for teenage readers and read widely beyond them — immediate, high-stakes, and rarely condescending.')
) as v(name, description)
where g.name = v.name
  and coalesce(nullif(btrim(g.description), ''), null) is null;

-- ── Verify ──────────────────────────────────────────────────────────────────
-- select count(*) filter (where coalesce(btrim(description),'') = '') as still_blank,
--        count(*) as total
-- from public.genres;

-- ── Revert ──────────────────────────────────────────────────────────────────
-- Sets these back to NULL. Only the generated text is removed; a description
-- edited by hand after this ran will also be cleared, so check before using.
-- update public.genres set description = null
-- where name in ('Adventure', 'Alien Invasion', 'American Gothic', 'American Literature', 'Apocalyptic', 'Art History', 'Asian-inspired Fantasy', 'Australian Gothic', 'Aviation', 'Celtic Fantasy', 'Chicano & Latinx Fiction', 'Children''s Fiction', 'Classic Literary Fiction', 'Classic Science Fiction', 'Cli-Fi & Eco-Fiction', 'Cosmic Horror', 'Court Intrigue', 'Crime Fiction', 'Crime Noir', 'Cult Fiction', 'Cultural Studies', 'Dark Academia', 'Dark Fantasy', 'Demons & Monsters', 'Dragons', 'Drama', 'Dying Earth', 'Dystopian', 'Eco-Fiction', 'Epic Fantasy', 'Epistolary Fiction', 'Espionage', 'Existential', 'Family Drama', 'Feminist Fiction', 'First Contact', 'Flintlock Fantasy', 'Folklore', 'Grief Memoir', 'Grimdark', 'Haunted Houses', 'Heist', 'Historical Fantasy', 'Identity & Belonging', 'Illustrated', 'Indigenous Horror', 'Inspirational', 'Irish Fiction', 'Japanese & East Asian Literary Fiction', 'Legal Thriller', 'LGBTQ+ Fiction', 'Literary Criticism', 'LitRPG', 'Medical Narrative', 'Memoir', 'Metafiction', 'Military Fantasy', 'Military Science Fiction', 'Modernist', 'Music Fiction', 'Paranormal', 'Philosophy', 'Political Fiction', 'Portal Fantasy', 'Post-Apocalyptic', 'Postmodern', 'Quest Fantasy', 'Romantic Fiction', 'Satire', 'Satirical Fiction', 'Scandinavian Horror', 'Science Fiction', 'Short Fiction', 'Southern Gothic', 'Space Opera', 'Spanish Literature', 'Speculative Fiction', 'Sports Fiction', 'Steampunk', 'Supernatural', 'Surrealism', 'Suspense', 'Techno-Horror', 'Theology', 'Thriller', 'Time Travel', 'Urban Fantasy', 'Victorian Fiction', 'Vikings & Norse', 'War Fiction', 'Werewolves', 'Western', 'Young Adult');
