-- v0.73: avatar set redrawn on the Seeing Book brand.
-- The 49 genre avatars (solid + outline) became one per genre family (16),
-- and the 10 standard avatars were redrawn. The old SVGs are deleted from
-- public/avatars, so every profile still pointing at one is remapped here:
-- genre -> its family's avatar, standard -> its redrawn counterpart.
-- Anything left over (should be none) falls back to null = initials.

with map(old_url, new_url) as (values
  ('/avatars/g-arthurian.svg', '/avatars/g-myth-and-folklore.svg'),
  ('/avatars/g-arthurian-o.svg', '/avatars/g-myth-and-folklore.svg'),
  ('/avatars/g-biography.svg', '/avatars/g-ideas-and-lives.svg'),
  ('/avatars/g-biography-o.svg', '/avatars/g-ideas-and-lives.svg'),
  ('/avatars/g-body-horror-transgressive.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-body-horror-transgressive-o.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-childrens-picture-book.svg', '/avatars/g-young-readers.svg'),
  ('/avatars/g-childrens-picture-book-o.svg', '/avatars/g-young-readers.svg'),
  ('/avatars/g-classic-older-gothic.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-classic-older-gothic-o.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-classics.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-classics-o.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-comedy-wit.svg', '/avatars/g-comedy-and-satire.svg'),
  ('/avatars/g-comedy-wit-o.svg', '/avatars/g-comedy-and-satire.svg'),
  ('/avatars/g-coming-of-age.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-coming-of-age-o.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-contemporary-fiction.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-contemporary-fiction-o.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-cozy-fantasy.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-cozy-fantasy-o.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-cyberpunk.svg', '/avatars/g-science-fiction.svg'),
  ('/avatars/g-cyberpunk-o.svg', '/avatars/g-science-fiction.svg'),
  ('/avatars/g-dark-epic-fantasy.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-dark-epic-fantasy-o.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-east-asian-literary-fiction.svg', '/avatars/g-place-and-period.svg'),
  ('/avatars/g-east-asian-literary-fiction-o.svg', '/avatars/g-place-and-period.svg'),
  ('/avatars/g-epic-poetry.svg', '/avatars/g-verse-and-stage.svg'),
  ('/avatars/g-epic-poetry-o.svg', '/avatars/g-verse-and-stage.svg'),
  ('/avatars/g-experimental-avant-garde.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-experimental-avant-garde-o.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-fairy-tale-retelling.svg', '/avatars/g-myth-and-folklore.svg'),
  ('/avatars/g-fairy-tale-retelling-o.svg', '/avatars/g-myth-and-folklore.svg'),
  ('/avatars/g-fantasy.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-fantasy-o.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-fantasy-romance.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-fantasy-romance-o.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-feminist-sapphic-gothic.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-feminist-sapphic-gothic-o.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-folk-horror.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-folk-horror-o.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-gothic-haunted-houses.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-gothic-haunted-houses-o.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-graphic-novel.svg', '/avatars/g-page-and-panel.svg'),
  ('/avatars/g-graphic-novel-o.svg', '/avatars/g-page-and-panel.svg'),
  ('/avatars/g-historical-fiction.svg', '/avatars/g-place-and-period.svg'),
  ('/avatars/g-historical-fiction-o.svg', '/avatars/g-place-and-period.svg'),
  ('/avatars/g-historical-romance.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-historical-romance-o.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-horror.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-horror-o.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-international-fiction.svg', '/avatars/g-place-and-period.svg'),
  ('/avatars/g-international-fiction-o.svg', '/avatars/g-place-and-period.svg'),
  ('/avatars/g-intimate-fiction.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-intimate-fiction-o.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-japanese-east-asian-horror.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-japanese-east-asian-horror-o.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-lgbtq-romance.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-lgbtq-romance-o.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-literary-fiction.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-literary-fiction-o.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-magical-realism.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-magical-realism-o.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-martial-arts.svg', '/avatars/g-adventure-and-action.svg'),
  ('/avatars/g-martial-arts-o.svg', '/avatars/g-adventure-and-action.svg'),
  ('/avatars/g-mystery.svg', '/avatars/g-crime-and-suspense.svg'),
  ('/avatars/g-mystery-o.svg', '/avatars/g-crime-and-suspense.svg'),
  ('/avatars/g-mythological-fantasy.svg', '/avatars/g-myth-and-folklore.svg'),
  ('/avatars/g-mythological-fantasy-o.svg', '/avatars/g-myth-and-folklore.svg'),
  ('/avatars/g-non-fiction.svg', '/avatars/g-ideas-and-lives.svg'),
  ('/avatars/g-non-fiction-o.svg', '/avatars/g-ideas-and-lives.svg'),
  ('/avatars/g-parenting-motherhood.svg', '/avatars/g-ideas-and-lives.svg'),
  ('/avatars/g-parenting-motherhood-o.svg', '/avatars/g-ideas-and-lives.svg'),
  ('/avatars/g-philosophical-fiction.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-philosophical-fiction-o.svg', '/avatars/g-the-literary-shelf.svg'),
  ('/avatars/g-psychological-fiction.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-psychological-fiction-o.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-romance.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-romance-o.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-sapphic-fantasy.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-sapphic-fantasy-o.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-sci-fi-speculative.svg', '/avatars/g-science-fiction.svg'),
  ('/avatars/g-sci-fi-speculative-o.svg', '/avatars/g-science-fiction.svg'),
  ('/avatars/g-slasher.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-slasher-o.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-smutty-corner.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-smutty-corner-o.svg', '/avatars/g-love-and-desire.svg'),
  ('/avatars/g-social-commentary.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-social-commentary-o.svg', '/avatars/g-society-and-self.svg'),
  ('/avatars/g-southern-american-gothic.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-southern-american-gothic-o.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-superhero-epic.svg', '/avatars/g-adventure-and-action.svg'),
  ('/avatars/g-superhero-epic-o.svg', '/avatars/g-adventure-and-action.svg'),
  ('/avatars/g-vampires.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-vampires-o.svg', '/avatars/g-gothic.svg'),
  ('/avatars/g-witches.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-witches-o.svg', '/avatars/g-fantasy.svg'),
  ('/avatars/g-zombies.svg', '/avatars/g-horror.svg'),
  ('/avatars/g-zombies-o.svg', '/avatars/g-horror.svg'),
  ('/avatars/s-bookmark.svg', '/avatars/s-bookmark.svg'),
  ('/avatars/s-classic-reader.svg', '/avatars/s-bookmark.svg'),
  ('/avatars/s-feather-light.svg', '/avatars/s-quill.svg'),
  ('/avatars/s-keeper-of-stories.svg', '/avatars/s-the-seer.svg'),
  ('/avatars/s-lamplight.svg', '/avatars/s-candlelight.svg'),
  ('/avatars/s-moon-reader.svg', '/avatars/s-moon-reader.svg'),
  ('/avatars/s-night-owl.svg', '/avatars/s-night-owl.svg'),
  ('/avatars/s-stacked-up.svg', '/avatars/s-stacked-up.svg'),
  ('/avatars/s-tea-pages.svg', '/avatars/s-tea-and-pages.svg'),
  ('/avatars/s-wanderer.svg', '/avatars/s-wanderer.svg')
)
update public.profiles p
   set avatar_url = map.new_url
  from map
 where p.avatar_url = map.old_url;

update public.profiles
   set avatar_url = null
 where avatar_url like '/avatars/%'
   and avatar_url not in (
     '/avatars/g-adventure-and-action.svg',
     '/avatars/g-comedy-and-satire.svg',
     '/avatars/g-crime-and-suspense.svg',
     '/avatars/g-fantasy.svg',
     '/avatars/g-gothic.svg',
     '/avatars/g-horror.svg',
     '/avatars/g-ideas-and-lives.svg',
     '/avatars/g-love-and-desire.svg',
     '/avatars/g-myth-and-folklore.svg',
     '/avatars/g-page-and-panel.svg',
     '/avatars/g-place-and-period.svg',
     '/avatars/g-science-fiction.svg',
     '/avatars/g-society-and-self.svg',
     '/avatars/g-the-literary-shelf.svg',
     '/avatars/g-verse-and-stage.svg',
     '/avatars/g-young-readers.svg',
     '/avatars/s-bookmark.svg',
     '/avatars/s-candlelight.svg',
     '/avatars/s-constellation.svg',
     '/avatars/s-moon-reader.svg',
     '/avatars/s-night-owl.svg',
     '/avatars/s-quill.svg',
     '/avatars/s-stacked-up.svg',
     '/avatars/s-tea-and-pages.svg',
     '/avatars/s-the-seer.svg',
     '/avatars/s-wanderer.svg'
   );
