-- v0.74 — Anthology insights. 2026-09-26.
-- Spec: docs/pro-tier-v1-spec.md §7 · Client: src/lib/anthologyInsights.js
--
-- Which of my Anthologies actually moves readers? Four signals per public
-- Anthology, all aggregate:
--   view    — the share page was opened (one per visitor per day)
--   open    — a book on it was opened from it (one per visitor per book per day)
--   add     — a signed-in reader shelved a book they reached through it
--   signup  — an account was created by someone whose last shared link was it
--
-- Privacy shape:
--   - No identities ever leave the server. The owner gets counts.
--   - `visitor` is a random id the browser generates (localStorage); it is
--     not derived from anything about the person and is never joined to an
--     account. It exists only to count unique visitors.
--   - The client does not log at all under Do Not Track / Global Privacy
--     Control.
--   - adds and signups are small numbers that could point at a person ("my
--     one friend who joined last week"), so they are reported only at 5 or
--     more. Below that the owner sees "fewer than 5".
--
-- Free owners see total views; Pro sees the breakdown and the ranking.
--
-- Idempotent.

create table if not exists public.anthology_events (
  id         bigint generated by default as identity primary key,
  list_id    uuid        not null references public.lists(id) on delete cascade,
  event      text        not null,
  visitor    text,
  user_id    uuid        references auth.users(id) on delete set null,
  book_key   text,
  day        date        not null default ((now() at time zone 'utc')::date),
  created_at timestamptz not null default now(),
  constraint anthology_events_event_check check (event in ('view', 'open', 'add', 'signup')),
  constraint anthology_events_visitor_len check (visitor is null or length(visitor) <= 64),
  constraint anthology_events_book_key_len check (book_key is null or length(book_key) <= 300)
);

-- De-duplication lives in the indexes, so a reload or a double click is a
-- no-op rather than a second row.
create unique index if not exists anthology_events_view_once
  on public.anthology_events (list_id, visitor, day) where event = 'view';
create unique index if not exists anthology_events_open_once
  on public.anthology_events (list_id, visitor, book_key, day) where event = 'open';
create unique index if not exists anthology_events_add_once
  on public.anthology_events (list_id, user_id, book_key) where event = 'add';
create unique index if not exists anthology_events_signup_once
  on public.anthology_events (user_id) where event = 'signup';
create index if not exists anthology_events_list_idx
  on public.anthology_events (list_id, event, created_at desc);

alter table public.anthology_events enable row level security;
-- No policies: nobody reads or writes this table except through the two
-- functions below.
revoke all on public.anthology_events from anon, authenticated;

comment on table public.anthology_events is
  'v0.74: aggregate Anthology signals. No identities are ever returned; see get_anthology_insights().';

-- ── Write ─────────────────────────────────────────────────────────────────────
create or replace function public.log_anthology_event (
  p_list_id  uuid,
  p_event    text,
  p_visitor  text DEFAULT NULL,
  p_book_key text DEFAULT NULL
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_uid     uuid := auth.uid();
  v_owner   uuid;
  v_public  boolean;
  v_created timestamptz;
begin
  if p_event not in ('view', 'open', 'add', 'signup') then return; end if;

  select user_id, is_public into v_owner, v_public from public.lists where id = p_list_id;
  if v_owner is null or not coalesce(v_public, false) then return; end if;

  -- The owner looking at their own Anthology is not an audience.
  if v_uid is not null and v_uid = v_owner then return; end if;

  if p_event in ('view', 'open') then
    if p_visitor is null or p_visitor !~ '^[0-9a-f-]{16,64}$' then return; end if;
    insert into public.anthology_events (list_id, event, visitor, book_key)
      values (p_list_id, p_event, p_visitor, left(p_book_key, 300))
      on conflict do nothing;

  elsif p_event = 'add' then
    if v_uid is null or p_book_key is null then return; end if;
    insert into public.anthology_events (list_id, event, user_id, book_key)
      values (p_list_id, 'add', v_uid, left(p_book_key, 300))
      on conflict do nothing;

  elsif p_event = 'signup' then
    -- Only a genuinely new account can be a referral: created in the last two
    -- days. Anything else is an existing reader replaying the call.
    if v_uid is null then return; end if;
    select created_at into v_created from public.profiles where id = v_uid;
    if v_created is null or v_created < now() - interval '2 days' then return; end if;
    insert into public.anthology_events (list_id, event, user_id)
      values (p_list_id, 'signup', v_uid)
      on conflict do nothing;
  end if;
end;
$function$;

revoke execute on function public.log_anthology_event(uuid, text, text, text) from public;
grant  execute on function public.log_anthology_event(uuid, text, text, text) to anon, authenticated;

-- ── Read ──────────────────────────────────────────────────────────────────────
create or replace function public.get_anthology_insights()
  RETURNS jsonb
  LANGUAGE plpgsql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_uid  uuid := auth.uid();
  v_pro  boolean;
  v_rows jsonb;
  v_k    constant integer := 5;
begin
  if v_uid is null then
    return jsonb_build_object('status', 'error', 'message', 'Not authenticated');
  end if;

  v_pro := public.is_pro(v_uid);

  with mine as (
    select id, title, is_public from public.lists where user_id = v_uid
  ),
  agg as (
    select m.id, m.title, m.is_public,
      count(*) filter (where e.event = 'view')                                              as views_all,
      count(*) filter (where e.event = 'view' and e.created_at > now() - interval '30 days') as views_30d,
      count(distinct e.visitor) filter (where e.event = 'view' and e.created_at > now() - interval '30 days') as visitors_30d,
      count(*) filter (where e.event = 'open' and e.created_at > now() - interval '30 days') as opens_30d,
      count(*) filter (where e.event = 'add')                                               as adds_all,
      count(*) filter (where e.event = 'signup')                                            as signups_all
    from mine m
    left join public.anthology_events e on e.list_id = m.id
    group by m.id, m.title, m.is_public
  ),
  fol as (
    select list_id, count(*) as followers
    from public.list_followers where list_id in (select id from mine)
    group by list_id
  )
  select coalesce(jsonb_agg(
    case when v_pro then jsonb_build_object(
      'list_id',      a.id,
      'title',        a.title,
      'is_public',    a.is_public,
      'views_all',    a.views_all,
      'views_30d',    a.views_30d,
      'visitors_30d', a.visitors_30d,
      'opens_30d',    a.opens_30d,
      'followers',    coalesce(f.followers, 0),
      'adds_all',     case when a.adds_all    >= v_k or a.adds_all    = 0 then a.adds_all    end,
      'signups_all',  case when a.signups_all >= v_k or a.signups_all = 0 then a.signups_all end
    ) else jsonb_build_object(
      'list_id',   a.id,
      'title',     a.title,
      'is_public', a.is_public,
      'views_all', a.views_all,
      'views_30d', a.views_30d
    ) end
    order by a.views_30d desc, a.views_all desc
  ), '[]'::jsonb)
  into v_rows
  from agg a left join fol f on f.list_id = a.id;

  return jsonb_build_object('status', 'ok', 'pro', v_pro, 'k', v_k, 'lists', v_rows);
end;
$function$;

revoke execute on function public.get_anthology_insights() from public, anon;
grant  execute on function public.get_anthology_insights() to authenticated;

do $$ begin
  raise notice 'v0.74: anthology_events + insights ready.';
end $$;
